try{importScripts('https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js');importScripts('https://www.gstatic.com/firebasejs/10.14.1/firebase-messaging-compat.js');firebase.initializeApp({apiKey:'AIzaSyAG3z8Uq40nGP1ofCcsFoMLcGZ4a4tsGhA',authDomain:'focuscal-connects.firebaseapp.com',projectId:'focuscal-connects',storageBucket:'focuscal-connects.firebasestorage.app',messagingSenderId:'570470010602',appId:'1:570470010602:web:4142ec4b57990c81581193'});firebase.messaging().onBackgroundMessage(payload=>{const n=payload.notification||{};self.registration.showNotification(n.title||'FocusCal',{body:n.body||'新しい更新があります',icon:'./icon-192.png',badge:'./icon-192.png',data:payload.data||{}})})}catch(e){console.warn('[FocusCal SW messaging unavailable/offline]',e)}
const CACHE='focuscal-v93-flight-ready',PREVIOUS='focuscal-v92-offline-first';
const CORE=['./','./index.html','./app.html','./manifest.json','./firebase-config.js','./icon-192.png','./icon-512.png','./peek.js','./enhancements.js','./ui-polish-v57.js','./feedback-v60.js','./push-config.js','./src/v70/account.js','./src/v70/collaboration.js','./src/v70/notifications.js','./src/v70/observability.js','./src/v76/feature-menu.js','./src/v82/year-wrap.js','./src/v91/peek-visual-sync.js','./src/v91/faithful-peek-lite.js','./src/v93/offline-resilience.js'];
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(CACHE);let shellOK=true;for(const url of CORE){try{const r=await fetch(url,{cache:'reload'});if(r.ok)await cache.put(url,r.clone());else if(url==='./index.html'||url==='./app.html')shellOK=false}catch(e){if(url==='./index.html'||url==='./app.html')shellOK=false;console.warn('[FocusCal precache]',url,e)}}if(shellOK)await self.skipWaiting()})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CACHE&&k!==PREVIOUS).map(k=>caches.delete(k)));await self.clients.claim()})()));
async function fallback(request,path){return await caches.match(request,{ignoreSearch:true})||await caches.match(path,{ignoreSearch:true})||await caches.match(path,{cacheName:PREVIOUS,ignoreSearch:true})}
async function cacheFirst(request,path){const hit=await fallback(request,path);if(hit)return hit;try{const fresh=await fetch(request);if(fresh.ok)(await caches.open(CACHE)).put(request,fresh.clone());return fresh}catch(_){return Response.error()}}
async function staleWhileRevalidate(request,path){const cached=await fallback(request,path);const refresh=fetch(request).then(async fresh=>{if(fresh.ok)(await caches.open(CACHE)).put(request,fresh.clone());return fresh}).catch(()=>null);return cached||await refresh||Response.error()}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==self.location.origin)return;if(event.request.mode==='navigate'){event.respondWith(staleWhileRevalidate(event.request,'./index.html'));return}event.respondWith(cacheFirst(event.request,url.pathname.endsWith('/app.html')?'./app.html':undefined))});
self.addEventListener('message',event=>{if(event.data?.type==='FOCUSCAL_OFFLINE_STATUS')event.source?.postMessage({type:'FOCUSCAL_OFFLINE_STATUS',cache:CACHE,ready:true})});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(ws=>{for(const w of ws){if('focus'in w)return w.focus()}return clients.openWindow('./')}))});