(()=>{'use strict';
const BUILD='89';
const COLORS={white:'#e8e8f0',silver:'#a0a8b8',red:'#e04848',crimson:'#c82858',coral:'#e87858',orange:'#e89038',gold:'#d6aa32',yellow:'#d8c840',lime:'#84b83c',green:'#3aa86a',emerald:'#2fb87a',teal:'#27a9a0',cyan:'#30a8d8',sky:'#5aa8e8',blue:'#4278d8',indigo:'#5b62d6',violet:'#8058d8',purple:'#9858c8',pink:'#d84f91',rose:'#dc6686',brown:'#9a7558',gray:'#73798a',black:'#444755'};
const THEMES={violet:['#7c5cfc','#a78bfa'],cyan:['#20a8d8','#64dcff'],green:['#28a860','#42d984'],gold:['#d09020','#f0c040'],red:['#d84050','#ff7888'],pink:['#d83888','#ff72bd'],blue:['#3570d8','#70a7ff'],mono:['#9292a8','#d2d2df'],galaxy:['#9858ff','#58c8ff'],sakura:['#e97aaa','#ffc0d8'],ocean:['#1888c8','#50d8f0'],ember:['#e06020','#ffb050'],matrix:['#28b860','#40ff88']};
const BGS={default:['#09090f','#0d0d16','#13131f','#191926','#22223a'],ink:['#000000','#050508','#0c0c12','#12121a','#1c1c28'],navy:['#060b18','#0a1020','#0f1628','#141d33','#1e2a44'],forest:['#04100b','#071610','#0b1e16','#10261c','#1a3628'],wine:['#120609','#180a0e','#221016','#2a151c','#3a1f28'],plum:['#0c0616','#110a1e','#1a1030','#20153a','#2c2048'],sand:['#0e0c08','#14110c','#1e1a12','#262118','#342d20'],slate:['#0b0d10','#101318','#171b22','#1e232c','#28303c'],teal:['#040f12','#06161a','#0a1f26','#0f2830','#183842']};
const CAT={work:'#3070d0',personal:'#8050d0',health:'#40a050',family:'#d07020',study:'#d0a020',event:'#c05090',other:'#607080'};
let db=null,auth=null,F=null,viewUid=null,viewName='FocusCal User',viewUnsub=null,lastInfo=null,remoteDays={},remoteAppearance={},loadingTimer=null;
const ownerWatches=new Map(),publishTimers=new Map();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const eventDocId=(uid,y,m)=>`${uid}_${y}_${m}`;
const readSettings=()=>{try{return JSON.parse(localStorage.getItem('fc_settings'))||{}}catch{return{}}};
const localWeekStart=()=>Number(readSettings().weekStart)===1?1:0;
const holidaysEnabled=()=>localStorage.getItem('fc_holidays_enabled')!=='0';
const appearance=()=>{const s=readSettings();return{theme:s.theme||'violet',bgTint:s.bgTint||'default',ambient:!!s.ambient,weekStart:Number(s.weekStart)||0,holidaysEnabled:holidaysEnabled()}};
const colorHex=v=>!v?null:/^#[0-9a-f]{6}$/i.test(String(v))?String(v):(COLORS[String(v)]||null);
const hexBg=(hex,f=.16)=>{if(!hex)return null;const r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16);return`rgb(${Math.round(r*f)},${Math.round(g*f)},${Math.round(b*f)})`};
const holiday=(y,m,d)=>{if(!holidaysEnabled())return null;try{return window.FocusCalHolidays?.get?.(y,m,d)||null}catch{return null}};
const monthInfo=()=>{const t=document.getElementById('peek-cal-title')?.textContent||'';const x=/(\d{4})年\s*(\d{1,2})月/.exec(t);return x?{y:+x[1],m:+x[2]-1}:null};
const STYLE=`
#peek-calendar.fc89-active #peek-cal-summary{display:none!important}#peek-calendar.fc89-active #peek-cal-events{position:relative!important;min-height:520px!important;transition:opacity .16s ease}#peek-calendar.fc89-loading #peek-cal-events{opacity:0!important;pointer-events:none!important}#peek-calendar.fc89-loading{position:relative}#peek-calendar.fc89-loading:after{content:'相手のカレンダーを同期中…';position:absolute;left:50%;top:118px;transform:translateX(-50%);z-index:20;color:#777796;font-size:.64rem;letter-spacing:.04em;white-space:nowrap}
.fc89-mirror{--a:#7c5cfc;--a2:#a78bfa;--bg:#09090f;--bg2:#0d0d16;--surface:#13131f;--surface2:#191926;--border:#22223a;position:relative;isolation:isolate;overflow:hidden;border:1px solid var(--border);border-radius:18px;background:linear-gradient(180deg,var(--bg),var(--bg2));min-height:520px;color:#eeeeff;box-shadow:0 18px 45px rgba(0,0,0,.22)}
.fc89-fx{position:absolute;inset:0;overflow:hidden;pointer-events:none;z-index:0}.fc89-blob{position:absolute;width:70%;aspect-ratio:1;border-radius:50%;filter:blur(52px);opacity:.28;animation:fc89Float 15s ease-in-out infinite alternate}.fc89-blob.b1{left:-28%;top:-18%;background:var(--a)}.fc89-blob.b2{right:-30%;bottom:-24%;background:var(--a2);animation-duration:19s}.fc89-blob.b3{left:28%;top:35%;width:44%;background:var(--a2);opacity:.12;animation-duration:23s}.fc89-stars{position:absolute;inset:0;background-image:radial-gradient(circle at 14% 18%,rgba(255,255,255,.8) 0 1px,transparent 1.7px),radial-gradient(circle at 68% 12%,rgba(255,255,255,.7) 0 1px,transparent 1.6px),radial-gradient(circle at 83% 31%,rgba(255,255,255,.52) 0 1px,transparent 1.5px),radial-gradient(circle at 31% 44%,rgba(255,255,255,.55) 0 1px,transparent 1.5px),radial-gradient(circle at 72% 65%,rgba(255,255,255,.62) 0 1px,transparent 1.5px);background-size:190px 160px;opacity:.44;animation:fc89Stars 18s linear infinite}.fc89-mirror:not(.ambient) .fc89-blob,.fc89-mirror:not(.ambient) .fc89-stars{display:none}.fc89-inner{position:relative;z-index:2;padding:14px 12px 18px}
.fc89-month{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:1px 2px 12px}.fc89-title{font-size:1.03rem;font-weight:800;letter-spacing:.06em;background:linear-gradient(100deg,var(--a),var(--a2),#fff,var(--a));background-size:260% 100%;-webkit-background-clip:text;background-clip:text;color:transparent;animation:fc89Title 8s linear infinite}.fc89-owner{font-size:.58rem;color:rgba(210,210,240,.55);margin-top:3px}.fc89-live{font-size:.52rem;color:#42d984}.fc89-live:before{content:'';display:inline-block;width:6px;height:6px;border-radius:50%;background:#42d984;margin-right:4px;box-shadow:0 0 9px #42d984}
.fc89-week{display:grid;grid-template-columns:repeat(7,1fr);gap:4px;margin-bottom:5px}.fc89-week span{text-align:center;font-size:.54rem;color:#777796;font-weight:700;padding:2px 0}.fc89-week .sun{color:#d96f7f}.fc89-week .sat{color:#5da8ea}.fc89-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:5px}.fc89-day{position:relative;min-height:68px;border:1px solid rgba(120,120,160,.14);border-radius:12px;background:color-mix(in srgb,var(--surface) 84%,transparent);padding:7px 6px 6px;overflow:hidden;color:#b9b9ce;text-align:left;transition:transform .12s,border-color .15s,background .15s;appearance:none;-webkit-appearance:none;opacity:1!important}.fc89-day.empty{background:transparent;border-color:transparent}.fc89-day.has-events{cursor:pointer}.fc89-day.has-events:active{transform:scale(.95)}.fc89-date{font-size:.72rem;font-weight:700;line-height:1}.fc89-day.sun .fc89-date{color:#e27486}.fc89-day.sat .fc89-date{color:#62afe9}.fc89-day.holiday .fc89-date{color:#d88798}.fc89-day.colored .fc89-date{color:#e7e7ef;font-weight:700}.fc89-holiday{position:absolute;right:5px;top:5px;font-size:6px;font-weight:900;width:11px;height:11px;border-radius:50%;display:grid;place-items:center;color:#df8295;border:1px solid rgba(220,112,132,.25);background:rgba(220,112,132,.08)}.fc89-dots{display:flex;gap:3px;flex-wrap:wrap;margin-top:8px}.fc89-dot{width:5px;height:5px;border-radius:50%;box-shadow:0 0 5px currentColor}.fc89-pill{margin-top:5px;padding:3px 4px;border-radius:5px;background:rgba(7,7,18,.48);font-size:.45rem;color:#a8a8c4;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.fc89-more{font-size:.42rem;color:var(--a2);margin-top:3px}
.fc89-day.fx-neon{animation:fc89Neon 2s ease-in-out infinite}.fc89-day.fx-sparkle{animation:fc89SparkGlow 2.4s ease-in-out infinite}.fc89-day.fx-sparkle:after{content:'✦';position:absolute;right:4px;bottom:4px;font-size:8px;color:var(--fx,#f0c040);animation:fc89Spark 1.6s ease-in-out infinite}.fc89-day.fx-rainbow{animation:fc89Rainbow 3.2s linear infinite}.fc89-day.fx-fire{border-color:#f07020!important;animation:fc89Fire .9s ease-in-out infinite}.fc89-day.fx-fire:after{content:'🔥';position:absolute;top:2px;right:3px;font-size:9px;animation:fc89FireDance 1.1s ease-in-out infinite}.fc89-day.fx-glitch{animation:fc89Glitch 2.4s steps(1) infinite}.fc89-day.fx-aurora{animation:fc89Aurora 5s ease-in-out infinite}.fc89-day.fx-glow{animation:fc89Neon 2.2s ease-in-out infinite}.fc89-day.fx-pulse{animation:fc89Pulse 1.8s ease-in-out infinite}.fc89-day.fx-shine:before{content:'';position:absolute;inset:-45%;background:linear-gradient(115deg,transparent 35%,rgba(255,255,255,.16) 50%,transparent 65%);transform:translateX(-75%);animation:fc89Shine 3.2s ease-in-out infinite;pointer-events:none}
.fc89-detail{display:none;position:absolute;inset:0;z-index:8;background:color-mix(in srgb,var(--bg) 93%,transparent);backdrop-filter:blur(13px);-webkit-backdrop-filter:blur(13px);padding:13px;overflow:auto}.fc89-detail.open{display:block;animation:fc89Detail .18s ease-out}.fc89-detail-head{display:flex;align-items:center;gap:9px;margin-bottom:14px}.fc89-back{width:34px;height:34px;border:1px solid var(--border);border-radius:10px;background:var(--surface2);color:#fff}.fc89-detail-title{font-size:.85rem;font-weight:850;flex:1}.fc89-event{border:1px solid var(--border);border-radius:13px;background:color-mix(in srgb,var(--surface) 90%,transparent);padding:11px;margin-bottom:9px}.fc89-event-line{display:flex;align-items:center;gap:7px}.fc89-cat{width:8px;height:8px;border-radius:50%;flex:none}.fc89-event-title{font-size:.75rem;font-weight:800;flex:1}.fc89-time{font-size:.59rem;color:#8a8aa7;margin-top:6px}.fc89-memo{font-size:.63rem;color:#b5b5cf;line-height:1.65;margin-top:8px;padding-top:8px;border-top:1px solid var(--border);white-space:pre-wrap}.fc89-done{opacity:.55}.fc89-done .fc89-event-title{text-decoration:line-through}
@keyframes fc89Float{to{transform:translate(18px,26px) scale(1.14) rotate(12deg)}}@keyframes fc89Stars{to{background-position:28px 40px}}@keyframes fc89Title{to{background-position:260% 0}}@keyframes fc89Neon{0%,100%{box-shadow:0 0 5px var(--fx,#7c5cfc),0 0 10px color-mix(in srgb,var(--fx,#7c5cfc) 40%,transparent)}50%{box-shadow:0 0 12px var(--fx,#7c5cfc),0 0 26px color-mix(in srgb,var(--fx,#7c5cfc) 60%,transparent)}}@keyframes fc89SparkGlow{0%,100%{box-shadow:0 0 4px color-mix(in srgb,var(--fx,#f0c040) 30%,transparent)}50%{box-shadow:0 0 12px color-mix(in srgb,var(--fx,#f0c040) 55%,transparent)}}@keyframes fc89Spark{50%{opacity:1;transform:scale(1.25) rotate(30deg)}}@keyframes fc89Rainbow{0%{border-color:#f05060;box-shadow:0 0 10px #f0506066}33%{border-color:#f0e040;box-shadow:0 0 10px #f0e04066}50%{border-color:#42d984;box-shadow:0 0 10px #42d98466}67%{border-color:#40a0f0;box-shadow:0 0 10px #40a0f066}83%{border-color:#a06cff;box-shadow:0 0 10px #a06cff66}100%{border-color:#f05060;box-shadow:0 0 10px #f0506066}}@keyframes fc89Fire{50%{box-shadow:0 0 12px #f0a030,0 0 24px #f0a03088}}@keyframes fc89FireDance{50%{transform:scale(1.2) rotate(5deg)}}@keyframes fc89Glitch{90%{box-shadow:-3px 0 0 #ff0050aa,3px 0 0 #00dcffaa;transform:translate(1.5px,-1px)}92%{transform:translate(-1.5px,1px)}96%,100%{transform:none}}@keyframes fc89Aurora{0%,100%{border-color:#42d984;box-shadow:0 0 10px #42d98466}33%{border-color:#40c8e8;box-shadow:0 0 12px #40c8e877}66%{border-color:#a06cff;box-shadow:0 0 12px #a06cff77}}@keyframes fc89Pulse{50%{transform:scale(.975);filter:brightness(1.14)}}@keyframes fc89Shine{55%,100%{transform:translateX(75%)}}@keyframes fc89Detail{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}
@media(max-width:390px){.fc89-day{min-height:61px;padding:6px 4px}.fc89-grid{gap:4px}.fc89-pill{font-size:.41rem}}@media(prefers-reduced-motion:reduce){.fc89-day[class*='fx-'],.fc89-blob,.fc89-stars,.fc89-title{animation:none!important}}
`;
function inject(){if(document.getElementById('fc89-style'))return;const s=document.createElement('style');s.id='fc89-style';s.textContent=STYLE;document.head.appendChild(s)}
function snapshotMonth(y,m){let raw={};try{raw=JSON.parse(localStorage.getItem(`fc_${y}_${m}`))||{}}catch{}const days={};for(const [day,dd] of Object.entries(raw)){if(!dd||typeof dd!=='object')continue;const events=Array.isArray(dd.events)?dd.events.filter(e=>e.peekVisibility!=='private').map(e=>{const busy=e.peekVisibility==='busy';return{title:busy?'予定あり':String(e.title||''),memo:busy?'':String(e.memo||''),cat:busy?'other':String(e.cat||'other'),pri:busy?'':String(e.pri||'med'),allday:!!e.allday,start:busy?'':String(e.start||''),end:busy?'':String(e.end||''),done:!!e.done,visibility:e.peekVisibility||'full'}}):[];const color=dd.color||null,effect=dd.effect||null;if(events.length||color||effect)days[day]={color,effect,events}}return days}
function localMirror(y,m){return{build:BUILD,days:snapshotMonth(y,m),appearance:appearance()}}
function sameMirror(a,b){try{return !!a&&JSON.stringify(a.days||{})===JSON.stringify(b.days||{})&&JSON.stringify(a.appearance||{})===JSON.stringify(b.appearance||{})}catch{return false}}
async function firebase(){if(db&&auth?.currentUser)return true;const cfg=window.FOCUSCAL_FIREBASE_CONFIG;if(!cfg)return false;try{const a=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),u=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js'),f=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js');const app=a.getApps().length?a.getApp():a.initializeApp(cfg);auth=u.getAuth(app);db=f.getFirestore(app);F={...f,...u};if(!auth.currentUser)await u.signInAnonymously(auth);return true}catch(e){console.warn('[v89 firebase]',e);return false}}
async function publishMonth(y,m){if(!(await firebase()))return;const key=`fc_${y}_${m}`;if(localStorage.getItem(key)==null)return;const mirrorV89=localMirror(y,m);try{await F.setDoc(F.doc(db,'events',eventDocId(auth.currentUser.uid,y,m)),{ownerUid:auth.currentUser.uid,mirrorV89,mirrorV89UpdatedAt:F.serverTimestamp()},{merge:true});console.debug('[v89 publish]',y,m,Object.keys(mirrorV89.days).length)}catch(e){console.warn('[v89 publish failed]',e.code,e.message)}}
function storedMonths(){const out=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i),x=/^fc_(\d{4})_(\d{1,2})$/.exec(k||'');if(x)out.push([+x[1],+x[2]])}return out}
function schedulePublish(y,m,delay=90){const k=`${y}_${m}`;clearTimeout(publishTimers.get(k));publishTimers.set(k,setTimeout(()=>{publishTimers.delete(k);publishMonth(y,m)},delay))}
async function watchOwnerMonth(y,m){if(!(await firebase()))return;const k=`${y}_${m}`;if(ownerWatches.has(k))return;const ref=F.doc(db,'events',eventDocId(auth.currentUser.uid,y,m));const stop=F.onSnapshot(ref,s=>{const local=localMirror(y,m),remote=s.exists()?s.data().mirrorV89:null;if(!sameMirror(remote,local))schedulePublish(y,m,45)},e=>console.warn('[v89 owner watch]',e.code,e.message));ownerWatches.set(k,stop)}
async function primeOwner(){if(!(await firebase()))return;for(const [y,m] of storedMonths()){watchOwnerMonth(y,m);schedulePublish(y,m,20)}}
function hookStorage(){if(Storage.prototype.setItem.__fcMirror89)return;const prev=Storage.prototype.setItem;const wrapped=function(k,v){const r=prev.call(this,k,v);try{const x=/^fc_(\d{4})_(\d{1,2})$/.exec(String(k));if(x){watchOwnerMonth(+x[1],+x[2]);schedulePublish(+x[1],+x[2],35)}else if(k==='fc_settings'||k==='fc_holidays_enabled')storedMonths().forEach(([y,m])=>schedulePublish(y,m,80))}catch{}return r};wrapped.__fcMirror89=true;Storage.prototype.setItem=wrapped}
function dayClass(y,m,d){const w=new Date(y,m,d).getDay();return w===0?'sun':w===6?'sat':''}
function effectName(d){return String(d?.effect||d?.fx||d?.cellEffect||'').toLowerCase().replace(/^fx-/,'')}
function eventTime(e){if(e.allday)return'終日';const s=e.start||'',n=e.end||'';return s&&n?`${s}–${n}`:s||n||''}
function openDay(d){const dd=remoteDays?.[d]||{},evs=Array.isArray(dd.events)?dd.events:[],detail=document.getElementById('fc89-detail'),mi=lastInfo;if(!detail||!mi||!evs.length)return;const h=holiday(mi.y,mi.m,d);detail.innerHTML=`<div class="fc89-detail-head"><button class="fc89-back" type="button">←</button><div class="fc89-detail-title">${mi.m+1}/${d}${h?` <span style="color:#d88798;font-size:.6rem">${esc(h)}</span>`:''}</div><span class="fc89-live">LIVE</span></div>${evs.map(e=>`<div class="fc89-event ${e.done?'fc89-done':''}"><div class="fc89-event-line"><span class="fc89-cat" style="background:${CAT[e.cat]||CAT.other}"></span><div class="fc89-event-title">${esc(e.title)}</div></div><div class="fc89-time">${esc(eventTime(e))}</div>${e.memo?`<div class="fc89-memo">${esc(e.memo)}</div>`:''}</div>`).join('')}`;detail.classList.add('open');detail.querySelector('.fc89-back').onclick=()=>detail.classList.remove('open')}
function render(source='v89'){const host=document.getElementById('peek-cal-events'),cal=document.getElementById('peek-calendar'),mi=lastInfo||monthInfo();if(!host||!cal||!mi||!viewUid)return;cal.classList.add('fc89-active');const a=remoteAppearance||{},t=THEMES[a.theme]||THEMES.violet,b=BGS[a.bgTint]||BGS.default,start=localWeekStart(),labels=start?['月','火','水','木','金','土','日']:['日','月','火','水','木','金','土'];const first=new Date(mi.y,mi.m,1).getDay(),offset=(first-start+7)%7,last=new Date(mi.y,mi.m+1,0).getDate(),cells=[];for(let i=0;i<offset;i++)cells.push('<div class="fc89-day empty"></div>');for(let d=1;d<=last;d++){const dd=remoteDays?.[d]||{},evs=Array.isArray(dd.events)?dd.events:[],hex=colorHex(dd.color||dd.colorKey),fx=effectName(dd),h=holiday(mi.y,mi.m,d),cls=['fc89-day',dayClass(mi.y,mi.m,d),evs.length?'has-events':'',h?'holiday':'',hex?'colored':'',fx?`fx-${['neon','sparkle','rainbow','fire','glitch','aurora','glow','pulse','shine'].includes(fx)?fx:'neon'}`:''].filter(Boolean).join(' '),style=[hex?`background:${hexBg(hex)}!important;border-color:${hex}!important;--fx:${hex}`:'',!hex&&fx?'--fx:#f0c040':''].filter(Boolean).join(';'),dots=evs.slice(0,4).map(e=>`<span class="fc89-dot" style="background:${CAT[e.cat]||CAT.other};color:${CAT[e.cat]||CAT.other}"></span>`).join(''),pill=evs[0]?`<div class="fc89-pill">${esc(evs[0].title)}</div>`:'',more=evs.length>1?`<div class="fc89-more">+${evs.length-1}</div>`:'';cells.push(`<button type="button" class="${cls}" data-fc89-day="${d}" ${evs.length?'':'disabled'} style="${style}"><span class="fc89-date">${d}</span>${h?'<span class="fc89-holiday">祝</span>':''}<div class="fc89-dots">${dots}</div>${pill}${more}</button>`)}const ambient=!!a.ambient||['galaxy','sakura','ocean','ember'].includes(a.theme);host.innerHTML=`<div class="fc89-mirror ${ambient?'ambient':''}" data-fc89-source="${esc(source)}" style="--a:${t[0]};--a2:${t[1]};--bg:${b[0]};--bg2:${b[1]};--surface:${b[2]};--surface2:${b[3]};--border:${b[4]}"><div class="fc89-fx"><div class="fc89-blob b1"></div><div class="fc89-blob b2"></div><div class="fc89-blob b3"></div><div class="fc89-stars"></div></div><div class="fc89-inner"><div class="fc89-month"><div><div class="fc89-title">${mi.y}年 ${mi.m+1}月</div><div class="fc89-owner">👀 ${esc(viewName)}さんのカレンダー</div></div><span class="fc89-live">LIVE</span></div><div class="fc89-week">${labels.map(x=>`<span class="${x==='日'?'sun':x==='土'?'sat':''}">${x}</span>`).join('')}</div><div class="fc89-grid">${cells.join('')}</div></div><div class="fc89-detail" id="fc89-detail"></div></div>`;host.querySelectorAll('[data-fc89-day]').forEach(x=>x.addEventListener('click',()=>openDay(+x.dataset.fc89Day)));cal.classList.remove('fc89-loading')}
function chooseSnapshot(data){const m89=data?.mirrorV89;if(m89?.days)return{days:m89.days,appearance:m89.appearance||{},source:'v89'};const m88=data?.mirrorV88;if(m88?.days)return{days:m88.days,appearance:m88.appearance||{},source:'v88'};const m87=data?.mirrorV87;if(m87?.days)return{days:m87.days,appearance:m87.appearance||{},source:'v87'};return{days:data?.richDays||data?.days||{},appearance:data?.appearance||{},source:'legacy'}}
async function subscribe(){const mi=monthInfo();if(!viewUid||!mi||!(await firebase()))return;lastInfo=mi;if(viewUnsub){try{viewUnsub()}catch{}}const ref=F.doc(db,'events',eventDocId(viewUid,mi.y,mi.m));let first=true;viewUnsub=F.onSnapshot(ref,s=>{const data=s.exists()?s.data():{},pick=chooseSnapshot(data);if(pick.source==='legacy'&&first){first=false;clearTimeout(loadingTimer);loadingTimer=setTimeout(()=>{remoteDays=pick.days;remoteAppearance=pick.appearance;render('legacy-fallback')},900);return}clearTimeout(loadingTimer);remoteDays=pick.days;remoteAppearance=pick.appearance;render(pick.source);first=false},e=>{console.warn('[v89 viewer]',e.code,e.message);document.getElementById('peek-calendar')?.classList.remove('fc89-loading')})}
function beginOpen(el){viewUid=el.dataset.peekOpen;viewName=el.closest('.peek-person')?.querySelector('.peek-person-name')?.textContent?.replace(/^👀\s*/,'')||'FocusCal User';const cal=document.getElementById('peek-calendar');cal?.classList.add('fc89-loading','fc89-active');requestAnimationFrame(()=>setTimeout(subscribe,0))}
function capture(){document.addEventListener('click',e=>{const open=e.target.closest?.('[data-peek-open]');if(open){beginOpen(open);return}if(e.target.closest?.('#peek-cal-prev,#peek-cal-next')){const cal=document.getElementById('peek-calendar');cal?.classList.add('fc89-loading');setTimeout(subscribe,80)}if(e.target.closest?.('#peek-cal-back')){clearTimeout(loadingTimer);if(viewUnsub){try{viewUnsub()}catch{}viewUnsub=null}viewUid=null;lastInfo=null}},true)}
function run(){inject();hookStorage();capture();setTimeout(primeOwner,250);setTimeout(primeOwner,1400);window.FocusCalFaithfulPeek={build:BUILD,render,subscribe,publishAll:primeOwner,mode:'self-healing-canonical-mirror'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();