(()=>{'use strict';
const BUILD='99';
const COLORS={white:'#e8e8f0',silver:'#a0a8b8',red:'#e04848',crimson:'#c82858',coral:'#e87858',orange:'#e89038',amber:'#e8a020',gold:'#d6aa32',yellow:'#d8c840',lime:'#84b83c',green:'#3aa86a',emerald:'#2fb87a',teal:'#27a9a0',cyan:'#30a8d8',sky:'#5aa8e8',blue:'#4278d8',indigo:'#5b62d6',violet:'#8058d8',purple:'#9858c8',pink:'#d84f91',magenta:'#c84ac8',fuchsia:'#cf42c8',rose:'#dc6686',brown:'#9a7558',gray:'#73798a',grey:'#73798a',black:'#444755'};
const THEMES={violet:['#7c5cfc','#a78bfa'],cyan:['#20a8d8','#64dcff'],green:['#28a860','#42d984'],gold:['#d09020','#f0c040'],red:['#d84050','#ff7888'],pink:['#d83888','#ff72bd'],blue:['#3570d8','#70a7ff'],mono:['#9292a8','#d2d2df'],galaxy:['#9858ff','#58c8ff'],sakura:['#e97aaa','#ffc0d8'],ocean:['#1888c8','#50d8f0'],ember:['#e06020','#ffb050'],matrix:['#28b860','#40ff88']};
const BGS={default:['#09090f','#0d0d16','#13131f','#191926','#22223a'],ink:['#000','#050508','#0c0c12','#12121a','#1c1c28'],navy:['#060b18','#0a1020','#0f1628','#141d33','#1e2a44'],forest:['#04100b','#071610','#0b1e16','#10261c','#1a3628'],wine:['#120609','#180a0e','#221016','#2a151c','#3a1f28'],plum:['#0c0616','#110a1e','#1a1030','#20153a','#2c2048'],sand:['#0e0c08','#14110c','#1e1a12','#262118','#342d20'],slate:['#0b0d10','#101318','#171b22','#1e232c','#28303c'],teal:['#040f12','#06161a','#0a1f26','#0f2830','#183842']};
let db,auth,F,uid=null,name='FocusCal User',year=new Date().getFullYear(),month=new Date().getMonth(),unsubs=[],data=new Map(),drag=null,animating=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const settings=()=>{try{return JSON.parse(localStorage.getItem('fc_settings'))||{}}catch{return{}}};
const weekStart=()=>Number(settings().weekStart)===1?1:0;
const docId=(u,y,m)=>`${u}_${y}_${m}`;
const key=(y,m)=>`${y}-${m}`;
function norm(y,m){while(m<0){m+=12;y--}while(m>11){m-=12;y++}return[y,m]}
const colorHex=v=>{if(!v)return null;const s=String(v).toLowerCase();return /^#[0-9a-f]{6}$/i.test(s)?s:COLORS[s]||null};
const hexBg=h=>h?`rgba(${parseInt(h.slice(1,3),16)},${parseInt(h.slice(3,5),16)},${parseInt(h.slice(5,7),16)},.16)`:null;
const holiday=(y,m,d)=>{if(localStorage.getItem('fc_holidays_enabled')==='0')return null;try{return window.FocusCalHolidays?.get?.(y,m,d)||null}catch{return null}};
const STYLE=`
#peek-calendar.fc99-active #peek-cal-summary{display:none!important}
#peek-calendar.fc99-active #peek-cal-events{min-height:0!important;overflow:hidden!important;padding:0!important;touch-action:pan-y}
#peek-calendar.fc99-active .peek-cal-head{margin-bottom:8px}
.fc99-shell{position:relative;width:100%;overflow:hidden;border-radius:16px;background:var(--pbg,#09090f);border:1px solid var(--pborder,#22223a);color:#eeeeff;touch-action:pan-y;user-select:none;-webkit-user-select:none}
.fc99-owner{display:flex;align-items:center;justify-content:space-between;padding:10px 12px 5px;position:relative;z-index:2}.fc99-owner b{font-size:.66rem;color:#777796}.fc99-live{font-size:.52rem;color:#42d984}.fc99-live:before{content:'';display:inline-block;width:6px;height:6px;border-radius:50%;background:#42d984;margin-right:4px;box-shadow:0 0 8px #42d984}
.fc99-week{display:grid;grid-template-columns:repeat(7,1fr);padding:3px 7px 5px;position:relative;z-index:2}.fc99-week span{text-align:center;font-size:.58rem;color:#777796}.fc99-week .sun{color:#c05050}.fc99-week .sat{color:#4070b0}
.fc99-viewport{overflow:hidden;width:100%;position:relative}.fc99-slider{display:flex;width:300%;transform:translate3d(-33.333333%,0,0);will-change:transform}.fc99-page{width:33.333333%;flex:none;padding:5px 7px 14px;box-sizing:border-box}.fc99-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:3px}
.fc99-day{border-radius:11px;padding:6px 3px 5px;min-height:84px;display:flex;flex-direction:column;align-items:center;gap:3px;background:var(--psurface,#13131f);border:1.5px solid transparent;position:relative;overflow:hidden;box-sizing:border-box;color:#b9b9ce}.fc99-day.empty{background:transparent}.fc99-day.sun .fc99-date{color:#c05050}.fc99-day.sat .fc99-date{color:#4070b0}.fc99-day.colored .fc99-date{color:#eeeeff}.fc99-date{font-size:.9rem;font-weight:500;line-height:1.1;min-height:18px}.fc99-holiday{position:absolute;top:3px;right:4px;font-size:.42rem;color:#d86878;border:1px solid #d8687855;border-radius:50%;width:13px;height:13px;display:grid;place-items:center}
.fc99-pills{width:100%;min-width:0;display:flex;flex-direction:column;gap:2px;position:relative}.fc99-pill{width:100%;min-width:0;border-radius:4px;background:rgba(5,5,15,.5);padding:2px 3px;box-sizing:border-box;font-size:.48rem;color:#9292b0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;line-height:1.35}.fc99-pill.done{text-decoration:line-through;opacity:.55}.fc99-more{font-size:.4rem;color:#777796;text-align:center}
.fc99-day.fx-neon{animation:fc99neon 2s ease-in-out infinite}.fc99-day.fx-sparkle:after{content:'✦';position:absolute;top:2px;right:3px;font-size:.55rem;color:var(--fx,#f0c040);animation:fc99spark 1.6s ease-in-out infinite}.fc99-day.fx-rainbow{animation:fc99rain 3.2s linear infinite}.fc99-day.fx-fire{border-color:#f07020!important;box-shadow:0 0 10px #f0702066}.fc99-day.fx-fire:after{content:'🔥';position:absolute;right:2px;bottom:2px;font-size:.6rem}.fc99-day.fx-glitch{box-shadow:-2px 0 #ff005077,2px 0 #00dcff77}.fc99-day.fx-aurora{box-shadow:0 0 12px #42d98455,inset 0 0 12px #a06cff33}.fc99-day.fx-glow{box-shadow:0 0 10px var(--fx,#7c5cfc)}.fc99-day.fx-pulse{animation:fc99pulse 2s ease-in-out infinite}
.fc99-detail{display:none;position:absolute;inset:0;z-index:10;background:rgba(9,9,15,.98);padding:14px;overflow:auto;-webkit-overflow-scrolling:touch}.fc99-detail.open{display:block}.fc99-detail-head{display:flex;align-items:center;gap:10px;margin-bottom:12px}.fc99-back{width:36px;height:36px;border:1px solid #2c2c46;border-radius:10px;background:#191926;color:#fff}.fc99-event{padding:11px;border:1px solid #22223a;border-radius:11px;background:#13131f;margin-bottom:8px}.fc99-event.done{opacity:.55}.fc99-event.done strong{text-decoration:line-through}.fc99-event strong{font-size:.75rem}.fc99-event small,.fc99-event p{display:block;font-size:.61rem;color:#9292b0;margin:6px 0 0;line-height:1.55}.fc99-event p{padding-top:6px;border-top:1px solid #22223a;white-space:pre-wrap}
@keyframes fc99neon{50%{box-shadow:0 0 12px var(--fx,#7c5cfc)}}@keyframes fc99spark{50%{opacity:.25;transform:scale(.75)}}@keyframes fc99pulse{50%{filter:brightness(1.15)}}@keyframes fc99rain{0%{border-color:#f05060}25%{border-color:#f0d040}50%{border-color:#42d984}75%{border-color:#40a0f0}100%{border-color:#f05060}}
@media(max-width:390px){.fc99-day{min-height:78px;padding:5px 2px}.fc99-grid{gap:3px}.fc99-pill{font-size:.44rem}}
@media(prefers-reduced-motion:reduce){.fc99-day{animation:none!important}}
`;
function inject(){if(document.getElementById('fc99-style'))return;const s=document.createElement('style');s.id='fc99-style';s.textContent=STYLE;document.head.appendChild(s)}
async function firebase(){if(db&&auth?.currentUser)return true;const cfg=window.FOCUSCAL_FIREBASE_CONFIG;if(!cfg)return false;try{const [a,u,f]=await Promise.all([import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js')]);const app=a.getApps().length?a.getApp():a.initializeApp(cfg);auth=u.getAuth(app);db=f.getFirestore(app);F={...f,...u};if(!auth.currentUser)await u.signInAnonymously(auth);return true}catch(e){console.warn('[v99 firebase]',e);return false}}
function appearance(){const d=data.get(key(year,month))||{};return d.appearance||{}}
function dayObj(d,n){return d?.days?.[n]||d?.days?.[String(n)]||{}}
function fxName(dd){return String(dd.effect||'').toLowerCase().replace(/^fx-/,'')}
function renderPage(y,m,d){
 const a=d?.appearance||appearance(),t=THEMES[a.theme]||THEMES.violet,b=BGS[a.bgTint]||BGS.default;
 const start=weekStart(),first=new Date(y,m,1).getDay(),off=(first-start+7)%7,last=new Date(y,m+1,0).getDate(),cells=[];
 for(let i=0;i<off;i++)cells.push('<div class="fc99-day empty"></div>');
 for(let n=1;n<=last;n++){const dd=dayObj(d,n),evs=Array.isArray(dd.events)?dd.events:[],w=new Date(y,m,n).getDay(),hex=colorHex(dd.color),fx=fxName(dd),h=holiday(y,m,n),cls=['fc99-day',w===0?'sun':w===6?'sat':'',hex?'colored':'',fx?`fx-${['neon','sparkle','rainbow','fire','glitch','aurora','glow','pulse'].includes(fx)?fx:'neon'}`:''].filter(Boolean).join(' '),sty=hex?`background:${hexBg(hex)};border-color:${hex};--fx:${hex}`:(fx?'--fx:#f0c040':'');
 const pills=evs.slice(0,2).map(e=>`<div class="fc99-pill ${e.done?'done':''}">${e.done?'✓':'·'} ${esc(e.allday?'':e.start?e.start+' ':'')}${esc(e.title)}</div>`).join('');
 cells.push(`<div class="${cls}" data-fc99-day="${n}" data-y="${y}" data-m="${m}" style="${sty}"><div class="fc99-date">${n}</div>${h?'<span class="fc99-holiday">祝</span>':''}<div class="fc99-pills">${pills}${evs.length>2?`<div class="fc99-more">+${evs.length-2}</div>`:''}</div></div>`)}
 return `<div class="fc99-page" style="--a:${t[0]};--a2:${t[1]};--psurface:${b[2]};--pborder:${b[4]}"><div class="fc99-grid">${cells.join('')}</div></div>`
}
function render(){
 const host=document.getElementById('peek-cal-events'),cal=document.getElementById('peek-calendar');if(!host||!cal||!uid)return;
 const a=appearance(),t=THEMES[a.theme]||THEMES.violet,b=BGS[a.bgTint]||BGS.default,start=weekStart(),labels=start?['月','火','水','木','金','土','日']:['日','月','火','水','木','金','土'];
 const [py,pm]=norm(year,month-1),[ny,nm]=norm(year,month+1);
 host.innerHTML=`<div class="fc99-shell" style="--a:${t[0]};--a2:${t[1]};--pbg:${b[0]};--psurface:${b[2]};--pborder:${b[4]}"><div class="fc99-owner"><b>👀 ${esc(name)}さんのカレンダー</b><span class="fc99-live">LIVE</span></div><div class="fc99-week">${labels.map(x=>`<span class="${x==='日'?'sun':x==='土'?'sat':''}">${x}</span>`).join('')}</div><div class="fc99-viewport"><div class="fc99-slider">${renderPage(py,pm,data.get(key(py,pm))||{})}${renderPage(year,month,data.get(key(year,month))||{})}${renderPage(ny,nm,data.get(key(ny,nm))||{})}</div></div><div class="fc99-detail"></div></div>`;
 document.getElementById('peek-cal-title').textContent=`${name}・${year}年${month+1}月`;cal.classList.add('fc99-active');bindCells();bindDrag();
}
function bindCells(){document.querySelectorAll('#peek-cal-events [data-fc99-day]').forEach(el=>el.onclick=()=>openDay(+el.dataset.y,+el.dataset.m,+el.dataset.fc99Day))}
function openDay(y,m,n){const dd=dayObj(data.get(key(y,m))||{},n),evs=Array.isArray(dd.events)?dd.events:[];if(!evs.length)return;const el=document.querySelector('.fc99-detail');if(!el)return;el.innerHTML=`<div class="fc99-detail-head"><button class="fc99-back">←</button><strong>${m+1}/${n}</strong><span class="fc99-live">LIVE</span></div>${evs.map(e=>`<div class="fc99-event ${e.done?'done':''}"><strong>${esc(e.title)}</strong><small>${esc(e.allday?'終日':[e.start,e.end].filter(Boolean).join('–'))}${e.done?' ✓':''}</small>${e.memo?`<p>${esc(e.memo)}</p>`:''}</div>`).join('')}`;el.classList.add('open');el.querySelector('.fc99-back').onclick=()=>el.classList.remove('open')}
function clearSubs(){unsubs.splice(0).forEach(x=>{try{x()}catch{}})}
async function subscribe3(){if(!uid||!(await firebase()))return;clearSubs();for(const delta of [-1,0,1]){const [y,m]=norm(year,month+delta),ref=F.doc(db,'events',docId(uid,y,m));unsubs.push(F.onSnapshot(ref,s=>{data.set(key(y,m),s.exists()?s.data():{});render()},e=>{console.warn('[v99]',e.code);data.set(key(y,m),data.get(key(y,m))||{});render()}))}}
function setMonth(y,m,dir=0){[year,month]=norm(y,m);render();subscribe3();if(dir)requestAnimationFrame(()=>{const sl=document.querySelector('.fc99-slider');if(!sl)return;sl.style.transition='none';sl.style.transform=`translate3d(${dir<0?'-66.666666%':'0%'},0,0)`;requestAnimationFrame(()=>{sl.style.transition='transform .34s cubic-bezier(.32,.72,.33,1)';sl.style.transform='translate3d(-33.333333%,0,0)'})})}
function move(delta){if(animating)return;const sl=document.querySelector('.fc99-slider');if(!sl){setMonth(year,month+delta);return}animating=true;sl.style.transition='transform .34s cubic-bezier(.32,.72,.33,1)';sl.style.transform=`translate3d(${delta>0?'-66.666666%':'0%'},0,0)`;setTimeout(()=>{animating=false;setMonth(year,month+delta)},350)}
function bindDrag(){const shell=document.querySelector('.fc99-shell'),sl=document.querySelector('.fc99-slider');if(!shell||!sl)return;let sx=0,sy=0,dx=0,active=false,horiz=false;
 shell.onpointerdown=e=>{if(e.target.closest('.fc99-detail,.fc99-back'))return;sx=e.clientX;sy=e.clientY;dx=0;active=true;horiz=false;sl.style.transition='none';try{shell.setPointerCapture(e.pointerId)}catch{}};
 shell.onpointermove=e=>{if(!active)return;dx=e.clientX-sx;const dy=e.clientY-sy;if(!horiz&&Math.abs(dy)>Math.abs(dx)+6){active=false;sl.style.transform='translate3d(-33.333333%,0,0)';return}if(Math.abs(dx)>6)horiz=true;if(horiz){e.preventDefault?.();const pct=dx/shell.clientWidth*33.333333;sl.style.transform=`translate3d(calc(-33.333333% + ${pct}%),0,0)`}};
 const end=e=>{if(!active)return;active=false;const threshold=Math.min(62,shell.clientWidth*.18);if(horiz&&Math.abs(dx)>threshold){move(dx<0?1:-1)}else{sl.style.transition='transform .25s cubic-bezier(.32,.72,.33,1)';sl.style.transform='translate3d(-33.333333%,0,0)'}};
 shell.onpointerup=end;shell.onpointercancel=end;
}
function remember(el){uid=el.dataset.peekOpen;name=el.closest('.peek-person')?.querySelector('.peek-person-name')?.textContent?.replace(/^👀\s*/,'')||'FocusCal User';year=Number(localStorage.getItem('fc_active_year'))||new Date().getFullYear();month=new Date().getMonth();data.clear();setTimeout(()=>{render();subscribe3()},0)}
function close(){clearSubs();uid=null;data.clear();document.getElementById('peek-calendar')?.classList.remove('fc99-active')}
function capture(){document.addEventListener('click',e=>{const op=e.target.closest?.('[data-peek-open]');if(op){remember(op);return}if(!uid)return;const prev=e.target.closest?.('#peek-cal-prev'),next=e.target.closest?.('#peek-cal-next');if(prev||next){e.preventDefault();e.stopImmediatePropagation();move(next?1:-1);return}if(e.target.closest?.('#peek-cal-back'))close()},true)}
function integrity(){const host=document.getElementById('peek-cal-events');if(!host||host.__fc99)return;host.__fc99=true;new MutationObserver(()=>{if(uid&&!host.querySelector('.fc99-shell'))setTimeout(render,0)}).observe(host,{childList:true})}
function init(n=0){inject();capture();const h=document.getElementById('peek-calendar');if(!h){if(n<100)setTimeout(()=>init(n+1),50);return}integrity();window.FocusCalFaithfulPeek={build:BUILD,mode:'shared-native-renderer-readonly-three-page-drag',render,move,subscribe:subscribe3,close}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>init(),{once:true});else init();
})();