(()=>{'use strict';
const BUILD='87';
const COLORS={white:'#e8e8f0',silver:'#a0a8b8',red:'#e04848',crimson:'#c82858',coral:'#e87858',orange:'#e89038',gold:'#d6aa32',yellow:'#d8c840',lime:'#84b83c',green:'#3aa86a',emerald:'#2fb87a',teal:'#27a9a0',cyan:'#30a8d8',sky:'#5aa8e8',blue:'#4278d8',indigo:'#5b62d6',violet:'#8058d8',purple:'#9858c8',pink:'#d84f91',rose:'#dc6686',brown:'#9a7558',gray:'#73798a',black:'#444755'};
const THEMES={violet:['#7c5cfc','#a78bfa'],cyan:['#20a8d8','#64dcff'],green:['#28a860','#42d984'],gold:['#d09020','#f0c040'],red:['#d84050','#ff7888'],pink:['#d83888','#ff72bd'],blue:['#3570d8','#70a7ff'],mono:['#9292a8','#d2d2df'],galaxy:['#9858ff','#58c8ff'],sakura:['#e97aaa','#ffc0d8'],ocean:['#1888c8','#50d8f0'],ember:['#e06020','#ffb050'],matrix:['#28b860','#40ff88']};
const BGS={default:['#09090f','#0d0d16','#13131f','#191926','#22223a'],ink:['#000000','#050508','#0c0c12','#12121a','#1c1c28'],navy:['#060b18','#0a1020','#0f1628','#141d33','#1e2a44'],forest:['#04100b','#071610','#0b1e16','#10261c','#1a3628'],wine:['#120609','#180a0e','#221016','#2a151c','#3a1f28'],plum:['#0c0616','#110a1e','#1a1030','#20153a','#2c2048'],sand:['#0e0c08','#14110c','#1e1a12','#262118','#342d20'],slate:['#0b0d10','#101318','#171b22','#1e232c','#28303c'],teal:['#040f12','#06161a','#0a1f26','#0f2830','#183842']};
let db=null,auth=null,F=null,viewUid=null,unsub=null,remoteDays={},remoteAppearance={},publishTimer=null;
const eventDocId=(uid,y,m)=>`${uid}_${y}_${m}`;
const readSettings=()=>{try{return JSON.parse(localStorage.getItem('fc_settings'))||{}}catch{return{}}};
const localWeekStart=()=>Number(readSettings().weekStart)===1?1:0;
const colorHex=v=>!v?null:/^#[0-9a-f]{6}$/i.test(v)?v:(COLORS[v]||null);
const hexBg=(hex,f=.16)=>{if(!hex)return null;const r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16);return`rgb(${Math.round(r*f)},${Math.round(g*f)},${Math.round(b*f)})`};
const monthInfo=()=>{const t=document.getElementById('peek-cal-title')?.textContent||document.querySelector('.fc-mirror-month-title')?.textContent||'';const x=/(\d{4})年\s*(\d{1,2})月/.exec(t);return x?{y:+x[1],m:+x[2]-1}:null};
const appearance=()=>{const s=readSettings();return{theme:s.theme||'violet',bgTint:s.bgTint||'default',weekStart:Number(s.weekStart)||0,holidaysEnabled:localStorage.getItem('fc_holidays_enabled')!=='0',ambient:!!s.ambient}};
const STYLE=`
.fc-mirror-week span{color:#777796!important}.fc-mirror-week span.v87-sun{color:#d96f7f!important}.fc-mirror-week span.v87-sat{color:#5da8ea!important}
.fc-mirror-day.v87-bg{background:var(--v87-bg)!important}.fc-mirror-day.v87-border{border-color:var(--v87-color)!important}.fc-mirror-day.v87-bg .fc-mirror-date{color:color-mix(in srgb,var(--v87-color) 38%,#fff)!important}
.fc-mirror-day.v87-fx-neon{animation:v87Neon 2s ease-in-out infinite}.fc-mirror-day.v87-fx-sparkle{animation:v87SparkGlow 2.4s ease-in-out infinite}.fc-mirror-day.v87-fx-sparkle:after{content:'✦';position:absolute;top:2px;right:3px;font-size:.55rem;color:var(--v87-fx,#f0c040);animation:v87Spark 1.6s ease-in-out infinite;pointer-events:none;z-index:4}.fc-mirror-day.v87-fx-rainbow{animation:v87Rainbow 3.2s linear infinite}.fc-mirror-day.v87-fx-fire{border-color:#f07020!important;animation:v87Fire .9s ease-in-out infinite}.fc-mirror-day.v87-fx-fire:after{content:'🔥';position:absolute;top:1px;right:2px;font-size:.6rem;animation:v87FireDance 1.1s ease-in-out infinite;pointer-events:none;z-index:4}.fc-mirror-day.v87-fx-glitch{animation:v87Glitch 2.4s steps(1) infinite}.fc-mirror-day.v87-fx-aurora{animation:v87Aurora 5s ease-in-out infinite}.fc-mirror-day.v87-fx-glow{animation:v87Neon 2.2s ease-in-out infinite}.fc-mirror-day.v87-fx-pulse{animation:v87Pulse 1.8s ease-in-out infinite}.fc-mirror-day.v87-fx-shine:before{content:'';position:absolute;inset:-45%;background:linear-gradient(115deg,transparent 35%,rgba(255,255,255,.16) 50%,transparent 65%);transform:translateX(-75%);animation:v87Shine 3.2s ease-in-out infinite;pointer-events:none;z-index:3}
@keyframes v87Neon{0%,100%{box-shadow:0 0 5px var(--v87-fx,#7c5cfc),0 0 10px color-mix(in srgb,var(--v87-fx,#7c5cfc) 40%,transparent)}50%{box-shadow:0 0 12px var(--v87-fx,#7c5cfc),0 0 26px color-mix(in srgb,var(--v87-fx,#7c5cfc) 60%,transparent)}}
@keyframes v87SparkGlow{0%,100%{box-shadow:0 0 4px color-mix(in srgb,var(--v87-fx,#f0c040) 30%,transparent)}50%{box-shadow:0 0 12px color-mix(in srgb,var(--v87-fx,#f0c040) 55%,transparent)}}@keyframes v87Spark{0%,100%{opacity:.2;transform:scale(.7) rotate(0)}50%{opacity:1;transform:scale(1.25) rotate(30deg)}}
@keyframes v87Rainbow{0%{border-color:#f05060;box-shadow:0 0 10px rgba(240,80,96,.4)}17%{border-color:#f0a040;box-shadow:0 0 10px rgba(240,160,64,.4)}33%{border-color:#f0e040;box-shadow:0 0 10px rgba(240,224,64,.4)}50%{border-color:#42d984;box-shadow:0 0 10px rgba(66,217,132,.4)}67%{border-color:#40a0f0;box-shadow:0 0 10px rgba(64,160,240,.4)}83%{border-color:#a06cff;box-shadow:0 0 10px rgba(160,108,255,.4)}100%{border-color:#f05060;box-shadow:0 0 10px rgba(240,80,96,.4)}}
@keyframes v87Fire{0%,100%{box-shadow:0 0 6px #f07020,0 0 14px rgba(240,112,32,.4)}30%{box-shadow:0 0 12px #f0a030,0 0 24px rgba(240,160,48,.55)}60%{box-shadow:0 0 8px #e05020,0 0 18px rgba(224,80,32,.45)}}@keyframes v87FireDance{0%,100%{transform:scale(1) rotate(-4deg)}50%{transform:scale(1.2) rotate(5deg)}}
@keyframes v87Glitch{0%,88%,100%{box-shadow:0 0 8px rgba(100,220,255,.3);transform:translate(0)}90%{box-shadow:-3px 0 0 rgba(255,0,80,.7),3px 0 0 rgba(0,220,255,.7);transform:translate(1.5px,-1px)}92%{box-shadow:3px 0 0 rgba(255,0,80,.7),-3px 0 0 rgba(0,220,255,.7);transform:translate(-1.5px,1px)}94%{transform:translate(1px,0)}96%{transform:translate(0)}}
@keyframes v87Aurora{0%,100%{border-color:#42d984;box-shadow:0 0 10px rgba(66,217,132,.4),inset 0 0 14px rgba(66,217,132,.08)}25%{border-color:#40c8e8;box-shadow:0 0 12px rgba(64,200,232,.45),inset 0 0 16px rgba(64,200,232,.09)}50%{border-color:#a06cff;box-shadow:0 0 12px rgba(160,108,255,.45),inset 0 0 16px rgba(160,108,255,.09)}75%{border-color:#f060a8;box-shadow:0 0 12px rgba(240,96,168,.45),inset 0 0 16px rgba(240,96,168,.09)}}@keyframes v87Pulse{50%{transform:scale(.975);filter:brightness(1.14)}}@keyframes v87Shine{55%,100%{transform:translateX(75%)}}
@media(prefers-reduced-motion:reduce){.fc-mirror-day[class*='v87-fx-']{animation:none!important}}
`;
function inject(){if(document.getElementById('v87-faithful-peek-style'))return;const s=document.createElement('style');s.id='v87-faithful-peek-style';s.textContent=STYLE;document.head.appendChild(s)}
function snapshotMonth(y,m){let raw={};try{raw=JSON.parse(localStorage.getItem(`fc_${y}_${m}`))||{}}catch{}const days={};for(const [day,dd] of Object.entries(raw)){if(!dd||typeof dd!=='object')continue;const events=Array.isArray(dd.events)?dd.events.filter(e=>e.peekVisibility!=='private').map(e=>{const busy=e.peekVisibility==='busy';return{title:busy?'予定あり':String(e.title||''),memo:busy?'':String(e.memo||''),cat:busy?'other':String(e.cat||'other'),pri:busy?'':String(e.pri||'med'),allday:!!e.allday,start:busy?'':String(e.start||''),end:busy?'':String(e.end||''),done:!!e.done,visibility:e.peekVisibility||'full'}}):[];const color=dd.color||null,effect=dd.effect||null;if(events.length||color||effect)days[day]={color,effect,events}}return days}
async function firebase(){if(db&&auth?.currentUser)return true;const cfg=window.FOCUSCAL_FIREBASE_CONFIG;if(!cfg)return false;try{const a=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),u=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js'),f=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js');const app=a.getApps().length?a.getApp():a.initializeApp(cfg);auth=u.getAuth(app);db=f.getFirestore(app);F={...f,...u};if(!auth.currentUser)await u.signInAnonymously(auth);return true}catch(e){console.warn('[v87 firebase]',e);return false}}
async function publishMonth(y,m){if(!(await firebase())||localStorage.getItem(`fc_${y}_${m}`)==null)return;const mirrorV87={build:BUILD,days:snapshotMonth(y,m),appearance:appearance()};try{await F.setDoc(F.doc(db,'events',eventDocId(auth.currentUser.uid,y,m)),{mirrorV87,mirrorV87UpdatedAt:F.serverTimestamp()},{merge:true})}catch(e){console.warn('[v87 publish]',e)}}
function allStoredMonths(){const out=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i),x=/^fc_(\d{4})_(\d{1,2})$/.exec(k||'');if(x)out.push([+x[1],+x[2]])}return out}
function publishAll(){allStoredMonths().forEach(([y,m])=>publishMonth(y,m))}
function schedule(y,m){clearTimeout(publishTimer);publishTimer=setTimeout(()=>publishMonth(y,m),360)}
function hookStorage(){if(Storage.prototype.setItem.__fcMirror87)return;const prev=Storage.prototype.setItem;const wrapped=function(k,v){const r=prev.call(this,k,v);try{const x=/^fc_(\d{4})_(\d{1,2})$/.exec(String(k));if(x)schedule(+x[1],+x[2]);else if(k==='fc_settings'||k==='fc_holidays_enabled')setTimeout(publishAll,420)}catch{}return r};wrapped.__fcMirror87=true;Storage.prototype.setItem=wrapped}
function reflowWeek(){const grid=document.querySelector('.fc-mirror-grid'),week=document.querySelector('.fc-mirror-week'),mi=monthInfo();if(!grid||!week||!mi)return;const start=localWeekStart(),labels=start?['月','火','水','木','金','土','日']:['日','月','火','水','木','金','土'];week.innerHTML=labels.map(x=>`<span class="${x==='日'?'v87-sun':x==='土'?'v87-sat':''}">${x}</span>`).join('');const cells=[...grid.querySelectorAll('[data-mirror-day]')].sort((a,b)=>+a.dataset.mirrorDay-+b.dataset.mirrorDay);if(!cells.length)return;grid.innerHTML='';const offset=(new Date(mi.y,mi.m,1).getDay()-start+7)%7;for(let i=0;i<offset;i++){const x=document.createElement('div');x.className='fc-mirror-day empty';grid.appendChild(x)}cells.forEach(c=>grid.appendChild(c))}
function applyTheme(){const root=document.querySelector('.fc-mirror');if(!root)return;const a=remoteAppearance||{},t=THEMES[a.theme]||THEMES.violet,b=BGS[a.bgTint]||BGS.default;[['--pm-a',t[0]],['--pm-a2',t[1]],['--pm-bg',b[0]],['--pm-bg2',b[1]],['--pm-surface',b[2]],['--pm-surface2',b[3]],['--pm-border',b[4]]].forEach(([k,v])=>root.style.setProperty(k,v));root.classList.toggle('ambient',!!a.ambient||['galaxy','sakura','ocean','ember'].includes(a.theme));root.classList.toggle('matrix',a.theme==='matrix')}
function clearLegacy(cell){[...cell.classList].filter(x=>x.startsWith('fc-shared-')||x.startsWith('fc-v85-')||x.startsWith('fc-v86-')||x.startsWith('v87-')).forEach(x=>cell.classList.remove(x));['--fc-cell-color','--fc-v85-color','--fc-v86-color','--fc-v86-fx','--v87-color','--v87-bg','--v87-fx'].forEach(k=>cell.style.removeProperty(k));cell.style.removeProperty('background');cell.style.removeProperty('border-color')}
function decorate(){applyTheme();document.querySelectorAll('.fc-mirror-grid [data-mirror-day]').forEach(cell=>{const d=remoteDays?.[+cell.dataset.mirrorDay]||{};clearLegacy(cell);const hex=colorHex(d.color);if(hex){cell.classList.add('v87-bg');cell.style.setProperty('--v87-color',hex);cell.style.setProperty('--v87-bg',hexBg(hex));cell.style.setProperty('--v87-fx',hex)}const effect=String(d.effect||'').toLowerCase().replace(/^fx-/,'');const borderAnimated=['rainbow','aurora','fire'].includes(effect);if(hex&&!borderAnimated)cell.classList.add('v87-border');if(effect){const ok=['neon','sparkle','rainbow','fire','glitch','aurora','glow','pulse','shine'];cell.classList.add(`v87-fx-${ok.includes(effect)?effect:'neon'}`)}})}
async function subscribe(){const mi=monthInfo();if(!viewUid||!mi||!(await firebase()))return;if(unsub){try{unsub()}catch{}}unsub=F.onSnapshot(F.doc(db,'events',eventDocId(viewUid,mi.y,mi.m)),s=>{const x=s.exists()?s.data():{},m=x.mirrorV87||null;remoteDays=m?.days||x.richDays||x.days||{};remoteAppearance=m?.appearance||x.appearance||{};requestAnimationFrame(()=>{reflowWeek();decorate()})},e=>console.warn('[v87 subscribe]',e))}
function capture(){document.addEventListener('click',e=>{const open=e.target.closest?.('[data-peek-open]');if(open){viewUid=open.dataset.peekOpen;setTimeout(subscribe,80)}if(e.target.closest?.('#peek-cal-prev,#peek-cal-next'))setTimeout(subscribe,120)},true)}
function observe(){let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(()=>{reflowWeek();decorate()},18)}).observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('storage',e=>{if(e.key==='fc_settings')reflowWeek()})}
function run(){inject();hookStorage();capture();observe();setTimeout(publishAll,500);setTimeout(()=>{reflowWeek();decorate()},650);window.FocusCalFaithfulPeek={build:BUILD,publishAll,subscribe,decorate,mode:'single-source-mirror'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();