(()=>{'use strict';
const BUILD='88';
const COLORS={white:'#e8e8f0',silver:'#a0a8b8',red:'#e04848',crimson:'#c82858',coral:'#e87858',orange:'#e89038',gold:'#d6aa32',yellow:'#d8c840',lime:'#84b83c',green:'#3aa86a',emerald:'#2fb87a',teal:'#27a9a0',cyan:'#30a8d8',sky:'#5aa8e8',blue:'#4278d8',indigo:'#5b62d6',violet:'#8058d8',purple:'#9858c8',pink:'#d84f91',rose:'#dc6686',brown:'#9a7558',gray:'#73798a',black:'#444755'};
const THEMES={violet:['#7c5cfc','#a78bfa'],cyan:['#20a8d8','#64dcff'],green:['#28a860','#42d984'],gold:['#d09020','#f0c040'],red:['#d84050','#ff7888'],pink:['#d83888','#ff72bd'],blue:['#3570d8','#70a7ff'],mono:['#9292a8','#d2d2df'],galaxy:['#9858ff','#58c8ff'],sakura:['#e97aaa','#ffc0d8'],ocean:['#1888c8','#50d8f0'],ember:['#e06020','#ffb050'],matrix:['#28b860','#40ff88']};
const BGS={default:['#09090f','#0d0d16','#13131f','#191926','#22223a'],ink:['#000000','#050508','#0c0c12','#12121a','#1c1c28'],navy:['#060b18','#0a1020','#0f1628','#141d33','#1e2a44'],forest:['#04100b','#071610','#0b1e16','#10261c','#1a3628'],wine:['#120609','#180a0e','#221016','#2a151c','#3a1f28'],plum:['#0c0616','#110a1e','#1a1030','#20153a','#2c2048'],sand:['#0e0c08','#14110c','#1e1a12','#262118','#342d20'],slate:['#0b0d10','#101318','#171b22','#1e232c','#28303c'],teal:['#040f12','#06161a','#0a1f26','#0f2830','#183842']};
const CAT={work:'#3070d0',personal:'#8050d0',health:'#40a050',family:'#d07020',study:'#d0a020',other:'#607080'};
let db=null,auth=null,F=null,viewUid=null,viewName='FocusCal User',unsub=null,remoteDays={},remoteAppearance={},lastInfo=null,publishTimers=new Map(),renderGuard=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const eventDocId=(uid,y,m)=>`${uid}_${y}_${m}`;
const readSettings=()=>{try{return JSON.parse(localStorage.getItem('fc_settings'))||{}}catch{return{}}};
const localWeekStart=()=>Number(readSettings().weekStart)===1?1:0;
const holidaysEnabled=()=>localStorage.getItem('fc_holidays_enabled')!=='0';
const colorHex=v=>!v?null:/^#[0-9a-f]{6}$/i.test(String(v))?String(v):COLORS[v]||null;
const hexBg=(hex,f=.16)=>{if(!hex)return null;const r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16);return`rgb(${Math.round(r*f)},${Math.round(g*f)},${Math.round(b*f)})`};
const appearance=()=>{const s=readSettings();return{theme:s.theme||'violet',bgTint:s.bgTint||'default',ambient:!!s.ambient,weekStart:Number(s.weekStart)||0,holidaysEnabled:holidaysEnabled()}};
const monthInfo=()=>{const t=document.getElementById('peek-cal-title')?.textContent||'';const x=/(\d{4})年\s*(\d{1,2})月/.exec(t);return x?{y:+x[1],m:+x[2]-1}:null};
const holiday=(y,m,d)=>{if(!holidaysEnabled())return null;try{return window.FocusCalHolidays?.get?.(y,m,d)||null}catch{return null}};
const STYLE=`
#peek-calendar.fc88-active #peek-cal-summary{display:none!important}#peek-calendar.fc88-active #peek-cal-events{position:relative!important;min-height:520px!important}
.fc88-mirror{--a:#7c5cfc;--a2:#a78bfa;--bg:#09090f;--bg2:#0d0d16;--surface:#13131f;--surface2:#191926;--border:#22223a;position:relative;isolation:isolate;overflow:hidden;border:1px solid var(--border);border-radius:18px;background:linear-gradient(180deg,var(--bg),var(--bg2));min-height:520px;color:#eeeeff;box-shadow:0 18px 45px rgba(0,0,0,.22)}
.fc88-fx{position:absolute;inset:0;overflow:hidden;pointer-events:none;z-index:0}.fc88-blob{position:absolute;width:70%;aspect-ratio:1;border-radius:50%;filter:blur(52px);opacity:.28;animation:fc88Float 15s ease-in-out infinite alternate}.fc88-blob.b1{left:-28%;top:-18%;background:var(--a)}.fc88-blob.b2{right:-30%;bottom:-24%;background:var(--a2);animation-duration:19s}.fc88-blob.b3{left:28%;top:35%;width:44%;background:var(--a2);opacity:.12;animation-duration:23s}.fc88-stars{position:absolute;inset:0;background-image:radial-gradient(circle at 14% 18%,rgba(255,255,255,.8) 0 1px,transparent 1.7px),radial-gradient(circle at 68% 12%,rgba(255,255,255,.7) 0 1px,transparent 1.6px),radial-gradient(circle at 83% 31%,rgba(255,255,255,.52) 0 1px,transparent 1.5px),radial-gradient(circle at 31% 44%,rgba(255,255,255,.55) 0 1px,transparent 1.5px),radial-gradient(circle at 72% 65%,rgba(255,255,255,.62) 0 1px,transparent 1.5px);background-size:190px 160px;opacity:.44;animation:fc88Stars 18s linear infinite}.fc88-mirror:not(.ambient) .fc88-blob,.fc88-mirror:not(.ambient) .fc88-stars{display:none}.fc88-inner{position:relative;z-index:2;padding:14px 12px 18px}
.fc88-month{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:1px 2px 12px}.fc88-title{font-size:1.03rem;font-weight:800;letter-spacing:.06em;background:linear-gradient(100deg,var(--a),var(--a2),#fff,var(--a));background-size:260% 100%;-webkit-background-clip:text;background-clip:text;color:transparent;animation:fc88Title 8s linear infinite}.fc88-owner{font-size:.58rem;color:rgba(210,210,240,.55);margin-top:3px}.fc88-live{font-size:.52rem;color:#42d984}.fc88-live:before{content:'';display:inline-block;width:6px;height:6px;border-radius:50%;background:#42d984;margin-right:4px;box-shadow:0 0 9px #42d984}
.fc88-week{display:grid;grid-template-columns:repeat(7,1fr);gap:4px;margin-bottom:5px}.fc88-week span{text-align:center;font-size:.54rem;color:#777796;font-weight:700;padding:2px 0}.fc88-week .sun{color:#d96f7f}.fc88-week .sat{color:#5da8ea}.fc88-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:5px}.fc88-day{position:relative;min-height:68px;border:1px solid rgba(120,120,160,.14);border-radius:12px;background:color-mix(in srgb,var(--surface) 84%,transparent);padding:7px 6px 6px;overflow:hidden;color:#b9b9ce;text-align:left;transition:transform .12s,border-color .15s,background .15s;appearance:none;-webkit-appearance:none}.fc88-day.empty{background:transparent;border-color:transparent}.fc88-day.has-events{cursor:pointer}.fc88-day.has-events:active{transform:scale(.95)}.fc88-date{font-size:.72rem;font-weight:700;line-height:1}.fc88-day.sun .fc88-date{color:#e27486}.fc88-day.sat .fc88-date{color:#62afe9}.fc88-day.holiday .fc88-date{color:#d88798}.fc88-day.colored .fc88-date{color:#ddd;font-weight:600}.fc88-holiday{position:absolute;right:5px;top:5px;font-size:6px;font-weight:900;width:11px;height:11px;border-radius:50%;display:grid;place-items:center;color:#df8295;border:1px solid rgba(220,112,132,.25);background:rgba(220,112,132,.08)}.fc88-dots{display:flex;gap:3px;flex-wrap:wrap;margin-top:8px}.fc88-dot{width:5px;height:5px;border-radius:50%;box-shadow:0 0 5px currentColor}.fc88-pill{margin-top:5px;padding:3px 4px;border-radius:5px;background:rgba(255,255,255,.045);font-size:.45rem;color:#9c9cb9;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.fc88-more{font-size:.42rem;color:var(--a2);margin-top:3px}
.fc88-day.fx-neon{animation:fc88Neon 2s ease-in-out infinite}.fc88-day.fx-sparkle{animation:fc88SparkGlow 2.4s ease-in-out infinite}.fc88-day.fx-sparkle:after{content:'✦';position:absolute;right:4px;bottom:4px;font-size:8px;color:var(--fx,#f0c040);animation:fc88Spark 1.6s ease-in-out infinite}.fc88-day.fx-rainbow{animation:fc88Rainbow 3.2s linear infinite}.fc88-day.fx-fire{border-color:#f07020!important;animation:fc88Fire .9s ease-in-out infinite}.fc88-day.fx-fire:after{content:'🔥';position:absolute;top:2px;right:3px;font-size:9px;animation:fc88FireDance 1.1s ease-in-out infinite}.fc88-day.fx-glitch{animation:fc88Glitch 2.4s steps(1) infinite}.fc88-day.fx-aurora{animation:fc88Aurora 5s ease-in-out infinite}.fc88-day.fx-glow{animation:fc88Neon 2.2s ease-in-out infinite}.fc88-day.fx-pulse{animation:fc88Pulse 1.8s ease-in-out infinite}.fc88-day.fx-shine:before{content:'';position:absolute;inset:-45%;background:linear-gradient(115deg,transparent 35%,rgba(255,255,255,.16) 50%,transparent 65%);transform:translateX(-75%);animation:fc88Shine 3.2s ease-in-out infinite;pointer-events:none}
.fc88-detail{display:none;position:absolute;inset:0;z-index:8;background:color-mix(in srgb,var(--bg) 93%,transparent);backdrop-filter:blur(13px);-webkit-backdrop-filter:blur(13px);padding:13px;overflow:auto}.fc88-detail.open{display:block;animation:fc88Detail .18s ease-out}.fc88-detail-head{display:flex;align-items:center;gap:9px;margin-bottom:14px}.fc88-back{width:34px;height:34px;border:1px solid var(--border);border-radius:10px;background:var(--surface2);color:#fff}.fc88-detail-title{font-size:.85rem;font-weight:850;flex:1}.fc88-event{border:1px solid var(--border);border-radius:13px;background:color-mix(in srgb,var(--surface) 90%,transparent);padding:11px;margin-bottom:9px}.fc88-event-line{display:flex;align-items:center;gap:7px}.fc88-cat{width:8px;height:8px;border-radius:50%;flex:none}.fc88-event-title{font-size:.75rem;font-weight:800;flex:1}.fc88-time{font-size:.59rem;color:#8a8aa7;margin-top:6px}.fc88-memo{font-size:.63rem;color:#b5b5cf;line-height:1.65;margin-top:8px;padding-top:8px;border-top:1px solid var(--border);white-space:pre-wrap}.fc88-done{opacity:.55}.fc88-done .fc88-event-title{text-decoration:line-through}
@keyframes fc88Float{to{transform:translate(18px,26px) scale(1.14) rotate(12deg)}}@keyframes fc88Stars{to{background-position:28px 40px}}@keyframes fc88Title{to{background-position:260% 0}}@keyframes fc88Neon{0%,100%{box-shadow:0 0 5px var(--fx,#7c5cfc),0 0 10px color-mix(in srgb,var(--fx,#7c5cfc) 40%,transparent)}50%{box-shadow:0 0 12px var(--fx,#7c5cfc),0 0 26px color-mix(in srgb,var(--fx,#7c5cfc) 60%,transparent)}}@keyframes fc88SparkGlow{0%,100%{box-shadow:0 0 4px color-mix(in srgb,var(--fx,#f0c040) 30%,transparent)}50%{box-shadow:0 0 12px color-mix(in srgb,var(--fx,#f0c040) 55%,transparent)}}@keyframes fc88Spark{50%{opacity:1;transform:scale(1.25) rotate(30deg)}}@keyframes fc88Rainbow{0%{border-color:#f05060;box-shadow:0 0 10px #f0506066}33%{border-color:#f0e040;box-shadow:0 0 10px #f0e04066}50%{border-color:#42d984;box-shadow:0 0 10px #42d98466}67%{border-color:#40a0f0;box-shadow:0 0 10px #40a0f066}83%{border-color:#a06cff;box-shadow:0 0 10px #a06cff66}100%{border-color:#f05060;box-shadow:0 0 10px #f0506066}}@keyframes fc88Fire{50%{box-shadow:0 0 12px #f0a030,0 0 24px #f0a03088}}@keyframes fc88FireDance{50%{transform:scale(1.2) rotate(5deg)}}@keyframes fc88Glitch{90%{box-shadow:-3px 0 0 #ff0050aa,3px 0 0 #00dcffaa;transform:translate(1.5px,-1px)}92%{transform:translate(-1.5px,1px)}96%,100%{transform:none}}@keyframes fc88Aurora{0%,100%{border-color:#42d984;box-shadow:0 0 10px #42d98466}33%{border-color:#40c8e8;box-shadow:0 0 12px #40c8e877}66%{border-color:#a06cff;box-shadow:0 0 12px #a06cff77}}@keyframes fc88Pulse{50%{transform:scale(.975);filter:brightness(1.14)}}@keyframes fc88Shine{55%,100%{transform:translateX(75%)}}@keyframes fc88Detail{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}
@media(max-width:390px){.fc88-day{min-height:61px;padding:6px 4px}.fc88-grid{gap:4px}.fc88-pill{font-size:.41rem}}@media(prefers-reduced-motion:reduce){.fc88-day[class*='fx-'],.fc88-blob,.fc88-stars,.fc88-title{animation:none!important}}
`;
function inject(){if(document.getElementById('fc88-style'))return;const s=document.createElement('style');s.id='fc88-style';s.textContent=STYLE;document.head.appendChild(s)}
function snapshotMonth(y,m){let raw={};try{raw=JSON.parse(localStorage.getItem(`fc_${y}_${m}`))||{}}catch{}const days={};for(const [day,dd] of Object.entries(raw)){if(!dd||typeof dd!=='object')continue;const events=Array.isArray(dd.events)?dd.events.filter(e=>e.peekVisibility!=='private').map(e=>{const busy=e.peekVisibility==='busy';return{title:busy?'予定あり':String(e.title||''),memo:busy?'':String(e.memo||''),cat:busy?'other':String(e.cat||'other'),pri:busy?'':String(e.pri||'med'),allday:!!e.allday,start:busy?'':String(e.start||''),end:busy?'':String(e.end||''),done:!!e.done,visibility:e.peekVisibility||'full'}}):[];const color=dd.color||null,effect=dd.effect||null;if(events.length||color||effect)days[day]={color,effect,events}}return days}
async function firebase(){if(db&&auth?.currentUser)return true;const cfg=window.FOCUSCAL_FIREBASE_CONFIG;if(!cfg)return false;try{const a=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),u=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js'),f=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js');const app=a.getApps().length?a.getApp():a.initializeApp(cfg);auth=u.getAuth(app);db=f.getFirestore(app);F={...f,...u};if(!auth.currentUser)await u.signInAnonymously(auth);return true}catch(e){console.warn('[v88 firebase]',e);return false}}
async function publishMonth(y,m){if(!(await firebase()))return;const key=`fc_${y}_${m}`;if(localStorage.getItem(key)==null)return;const payload={ownerUid:auth.currentUser.uid,mirrorV88:{build:BUILD,days:snapshotMonth(y,m),appearance:appearance()},mirrorV88UpdatedAt:F.serverTimestamp()};try{await F.setDoc(F.doc(db,'events',eventDocId(auth.currentUser.uid,y,m)),payload,{merge:true});console.debug('[v88 publish]',y,m,Object.keys(payload.mirrorV88.days).length)}catch(e){console.warn('[v88 publish failed]',e.code,e.message)}}
function storedMonths(){const out=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i),x=/^fc_(\d{4})_(\d{1,2})$/.exec(k||'');if(x)out.push([+x[1],+x[2]])}return out}
function publishAll(){storedMonths().forEach(([y,m])=>publishMonth(y,m))}
function schedulePublish(y,m){const k=`${y}_${m}`;clearTimeout(publishTimers.get(k));publishTimers.set(k,setTimeout(()=>{publishTimers.delete(k);publishMonth(y,m)},220))}
function hookStorage(){if(Storage.prototype.setItem.__fcMirror88)return;const prev=Storage.prototype.setItem;const wrapped=function(k,v){const r=prev.call(this,k,v);try{const x=/^fc_(\d{4})_(\d{1,2})$/.exec(String(k));if(x)schedulePublish(+x[1],+x[2]);else if(k==='fc_settings'||k==='fc_holidays_enabled')setTimeout(publishAll,260)}catch{}return r};wrapped.__fcMirror88=true;Storage.prototype.setItem=wrapped}
function dayClass(y,m,d){const w=new Date(y,m,d).getDay();return w===0?'sun':w===6?'sat':''}
function effectName(d){return String(d?.effect||d?.fx||d?.cellEffect||'').toLowerCase().replace(/^fx-/,'')}
function eventTime(e){if(e.allday)return'終日';const s=e.start||'',n=e.end||'';return s&&n?`${s}–${n}`:s||n||''}
function render(){const host=document.getElementById('peek-cal-events'),cal=document.getElementById('peek-calendar'),mi=lastInfo||monthInfo();if(!host||!cal||!mi||!viewUid)return;renderGuard=true;cal.classList.add('fc88-active');const a=remoteAppearance||{},t=THEMES[a.theme]||THEMES.violet,b=BGS[a.bgTint]||BGS.default,start=localWeekStart(),labels=start?['月','火','水','木','金','土','日']:['日','月','火','水','木','金','土'];const first=new Date(mi.y,mi.m,1).getDay(),offset=(first-start+7)%7,last=new Date(mi.y,mi.m+1,0).getDate(),cells=[];for(let i=0;i<offset;i++)cells.push('<div class="fc88-day empty"></div>');for(let d=1;d<=last;d++){const dd=remoteDays?.[d]||{},evs=Array.isArray(dd.events)?dd.events:[],hex=colorHex(dd.color||dd.colorKey),fx=effectName(dd),h=holiday(mi.y,mi.m,d),cls=['fc88-day',dayClass(mi.y,mi.m,d),evs.length?'has-events':'',h?'holiday':'',hex?'colored':'',fx?`fx-${['neon','sparkle','rainbow','fire','glitch','aurora','glow','pulse','shine'].includes(fx)?fx:'neon'}`:''].filter(Boolean).join(' '),style=[hex?`background:${hexBg(hex)}!important;border-color:${hex}!important;--fx:${hex}`:'',!hex&&fx?'--fx:#f0c040':''].filter(Boolean).join(';'),dots=evs.slice(0,4).map(e=>`<span class="fc88-dot" style="background:${CAT[e.cat]||CAT.other};color:${CAT[e.cat]||CAT.other}"></span>`).join(''),pill=evs[0]?`<div class="fc88-pill">${esc(evs[0].title)}</div>`:'',more=evs.length>1?`<div class="fc88-more">+${evs.length-1}</div>`:'';cells.push(`<button type="button" class="${cls}" data-fc88-day="${d}" ${evs.length?'':'disabled'} style="${style}"><span class="fc88-date">${d}</span>${h?'<span class="fc88-holiday">祝</span>':''}<div class="fc88-dots">${dots}</div>${pill}${more}</button>`)}const ambient=!!a.ambient||['galaxy','sakura','ocean','ember'].includes(a.theme);host.innerHTML=`<div class="fc88-mirror ${ambient?'ambient':''}" data-fc88-source="${esc(a.__source||'remote')}" style="--a:${t[0]};--a2:${t[1]};--bg:${b[0]};--bg2:${b[1]};--surface:${b[2]};--surface2:${b[3]};--border:${b[4]}"><div class="fc88-fx"><div class="fc88-blob b1"></div><div class="fc88-blob b2"></div><div class="fc88-blob b3"></div><div class="fc88-stars"></div></div><div class="fc88-inner"><div class="fc88-month"><div><div class="fc88-title">${mi.y}年 ${mi.m+1}月</div><div class="fc88-owner">👀 ${esc(viewName)}さんのカレンダー</div></div><span class="fc88-live">LIVE</span></div><div class="fc88-week">${labels.map(x=>`<span class="${x==='日'?'sun':x==='土'?'sat':''}">${x}</span>`).join('')}</div><div class="fc88-grid">${cells.join('')}</div></div><div class="fc88-detail" id="fc88-detail"></div></div>`;host.querySelectorAll('[data-fc88-day]').forEach(x=>x.addEventListener('click',()=>openDay(+x.dataset.fc88Day)));queueMicrotask(()=>{renderGuard=false})}
function openDay(d){const dd=remoteDays?.[d]||{},evs=Array.isArray(dd.events)?dd.events:[],detail=document.getElementById('fc88-detail'),mi=lastInfo;if(!detail||!mi||!evs.length)return;const h=holiday(mi.y,mi.m,d);detail.innerHTML=`<div class="fc88-detail-head"><button class="fc88-back" type="button">←</button><div class="fc88-detail-title">${mi.m+1}/${d}${h?` <span style="color:#d88798;font-size:.6rem">${esc(h)}</span>`:''}</div><span class="fc88-live">LIVE</span></div>${evs.map(e=>`<div class="fc88-event ${e.done?'fc88-done':''}"><div class="fc88-event-line"><span class="fc88-cat" style="background:${CAT[e.cat]||CAT.other}"></span><div class="fc88-event-title">${esc(e.title)}</div></div><div class="fc88-time">${esc(eventTime(e))}</div>${e.memo?`<div class="fc88-memo">${esc(e.memo)}</div>`:''}</div>`).join('')}`;detail.classList.add('open');detail.querySelector('.fc88-back').onclick=()=>detail.classList.remove('open')}
async function subscribe(){const mi=monthInfo();if(!viewUid||!mi||!(await firebase()))return;lastInfo=mi;if(unsub){try{unsub()}catch{}}unsub=F.onSnapshot(F.doc(db,'events',eventDocId(viewUid,mi.y,mi.m)),snap=>{const x=snap.exists()?snap.data():{},v88=x.mirrorV88,v87=x.mirrorV87;let source='legacy';if(v88?.days){remoteDays=v88.days;remoteAppearance=v88.appearance||{};source='v88'}else if(v87?.days){remoteDays=v87.days;remoteAppearance=v87.appearance||{};source='v87'}else{remoteDays=x.richDays||x.days||{};remoteAppearance=x.appearance||{}}remoteAppearance={...remoteAppearance,__source:source};console.debug('[v88 subscribe]',source,Object.keys(remoteDays||{}).length);render()},e=>console.warn('[v88 subscribe failed]',e.code,e.message))}
function capture(){document.addEventListener('click',e=>{const open=e.target.closest?.('[data-peek-open]');if(open){viewUid=open.dataset.peekOpen;viewName=open.closest('.peek-person')?.querySelector('.peek-person-name')?.textContent?.replace(/^👀\s*/,'')||'FocusCal User';setTimeout(subscribe,90);return}if(e.target.closest?.('#peek-cal-prev,#peek-cal-next'))setTimeout(subscribe,140);if(e.target.closest?.('#peek-cal-back')){if(unsub){try{unsub()}catch{}unsub=null}viewUid=null}},true)}
function protectRenderer(){const host=document.getElementById('peek-cal-events');if(!host)return;new MutationObserver(()=>{if(renderGuard||!viewUid||!lastInfo)return;if(!host.querySelector(':scope > .fc88-mirror'))requestAnimationFrame(render)}).observe(host,{childList:true,subtree:false})}
function observeMount(){const attach=()=>{protectRenderer();const cal=document.getElementById('peek-calendar');if(cal)cal.dataset.fc88Build=BUILD};if(document.getElementById('peek-cal-events'))attach();else{const mo=new MutationObserver(()=>{if(document.getElementById('peek-cal-events')){mo.disconnect();attach()}});mo.observe(document.body,{subtree:true,childList:true})}}
function run(){inject();hookStorage();capture();observeMount();setTimeout(publishAll,450);setTimeout(publishAll,1800);window.FocusCalFaithfulPeek={build:BUILD,publishAll,subscribe,render,mode:'canonical-single-renderer'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();