(()=>{'use strict';
const BUILD='73',PRESERVE=new Set(['btn-today','btn-prev','btn-next','btn-undo','btn-redo','settings-btn']);
const LABELS={'feedback-btn':'フィードバック','fc-feedback-btn':'フィードバック','peek-btn':'覗かせて頂く','fc-peek-btn':'覗かせて頂く','fc-ai-btn':'自動予定最適化','fc-account-btn':'アカウント','fc-collab-btn':'共同スペース','fc-notify-btn':'通知センター','pb-open':'フレーズ帳','fit-open':'筋トレ記録','party-open':'お祝い'};
const CSS=`#header-row{overflow:visible!important;min-width:0!important}#settings-btn{display:flex!important;visibility:visible!important;opacity:1!important;flex:0 0 auto!important;order:99!important}#fab-wrap .fc-v73-action{display:flex!important;align-items:center!important;justify-content:center!important;position:relative!important}#fab-wrap .fc-v73-action .fab-label{pointer-events:none}@media(max-width:520px){#header-row{gap:6px!important}#fab-wrap .fc-v73-action{width:54px;height:54px;border-radius:50%;font-size:1.18rem}}`;
function style(){if(document.getElementById('fc-v73-header-style'))return;const s=document.createElement('style');s.id='fc-v73-header-style';s.textContent=CSS;document.head.appendChild(s)}
function fabWrap(){return document.getElementById('fab-wrap')||document.getElementById('fab-menu')||document.querySelector('.fab-wrap')||document.getElementById('fab-container')}
function labelFor(b){return LABELS[b.id]||b.getAttribute('aria-label')||b.title||'機能'}
function isFeatureButton(b){if(!b||b.id==='fab-main'||PRESERVE.has(b.id))return false;if(LABELS[b.id])return true;if(b.matches('.nav-btn,[data-fc-secondary-action]'))return true;const t=`${b.title||''} ${b.getAttribute('aria-label')||''} ${(b.textContent||'').trim()}`;return /フィードバック|覗|自動予定|アカウント|共同|通知|フレーズ|筋トレ|お祝い|💬|🧠|👤|🤝|🔔/.test(t)}
function move(b){if(!isFeatureButton(b)||b.dataset.fcV73Moved==='1')return;const wrap=fabWrap(),main=document.getElementById('fab-main');if(!wrap||!main)return;b.dataset.fcV73Moved='1';b.classList.remove('nav-btn');b.classList.add('fab-item','fc-v73-action');if(!b.querySelector('.fab-label')){const sp=document.createElement('span');sp.className='fab-label';sp.textContent=labelFor(b);b.appendChild(sp)}wrap.insertBefore(b,main);b.setAttribute('data-fc-secondary-action','1');if(!b.getAttribute('aria-label'))b.setAttribute('aria-label',labelFor(b))}
function clean(){style();const settings=document.getElementById('settings-btn');if(settings){settings.hidden=false;settings.style.setProperty('display','flex','important');settings.style.setProperty('visibility','visible','important');settings.style.setProperty('opacity','1','important')}
  /* Structural rule: scan the whole document, not just #header-row. Older modules insert feature controls as siblings or into wrappers around the header. */
  document.querySelectorAll('button').forEach(move);
  Object.keys(LABELS).forEach(id=>move(document.getElementById(id)));
}
function boot(){clean();let t;const mo=new MutationObserver(()=>{clearTimeout(t);t=setTimeout(clean,10)});mo.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class','style','hidden']});[0,50,150,300,700,1400,2600,5000].forEach(ms=>setTimeout(clean,ms));window.addEventListener('focuscal:data-changed',clean);window.FocusCalHeaderCleanup={clean,build:BUILD,preserved:[...PRESERVE]}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();