(()=>{'use strict';
const BUILD='70',$=s=>document.querySelector(s);let auth,db,F;
const CSS=`#fc-account-overlay{display:none;position:fixed;inset:0;z-index:197;background:rgba(4,4,10,.78);backdrop-filter:blur(10px);align-items:flex-end;justify-content:center}#fc-account-overlay.open{display:flex}#fc-account-sheet{width:min(720px,100%);max-height:92dvh;overflow:auto;background:var(--surface,#13131f);border:1px solid var(--border2,#2c2c46);border-radius:22px 22px 0 0;padding:12px 16px 30px}.fc-ac-title{font-weight:900;font-size:.9rem;margin:8px 0 4px}.fc-ac-sub,.fc-ac-meta{font-size:.58rem;color:var(--muted);line-height:1.65}.fc-ac-card{padding:13px;border:1px solid var(--border);border-radius:14px;margin-top:12px;background:rgba(255,255,255,.025)}.fc-ac-btn{width:100%;margin-top:8px;border:1px solid var(--border2);background:var(--surface2);color:var(--text);border-radius:11px;padding:11px;font-weight:800}.fc-ac-btn.primary{background:linear-gradient(135deg,var(--accent),var(--accent2));border:0;color:#fff}.fc-ac-ok{color:#65d89a}.fc-ac-warn{color:#f0c06b}`;
async function firebase(){if(auth)return true;const cfg=window.FOCUSCAL_FIREBASE_CONFIG;if(!cfg)return false;const appM=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),authM=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js'),fsM=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js');const app=appM.getApps().length?appM.getApp():appM.initializeApp(cfg);auth=authM.getAuth(app);db=fsM.getFirestore(app);F={...authM,...fsM};if(!auth.currentUser)await authM.signInAnonymously(auth);return true}
function providers(){return auth?.currentUser?.providerData?.map(x=>x.providerId)||[]}
function monthKeys(){const out=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(/^fc_\d{4}_\d{1,2}$/.test(k||''))out.push(k)}return out}
async function backup(){await firebase();const uid=auth.currentUser.uid;status('クラウド保存中…');const payload={settings:JSON.parse(localStorage.getItem('fc_settings')||'{}'),holidays:localStorage.getItem('fc_holidays_enabled')!=='0',updatedAt:F.serverTimestamp(),accountBuild:BUILD};await F.setDoc(F.doc(db,'users',uid),payload,{merge:true});const keys=monthKeys();await Promise.all(keys.map(async k=>{let data={};try{data=JSON.parse(localStorage.getItem(k)||'{}')}catch{};await F.setDoc(F.doc(db,'calendarBackups',`${uid}_${k.slice(3)}`),{ownerUid:uid,storageKey:k,data,updatedAt:F.serverTimestamp()},{merge:true})}));status(`☁️ 設定とカレンダー ${keys.length}か月分をクラウド保存しました。`,'ok')}
async function restore(){await firebase();const uid=auth.currentUser.uid;status('復元中…');const s=await F.getDoc(F.doc(db,'users',uid));if(s.exists()){const d=s.data();if(d.settings)localStorage.setItem('fc_settings',JSON.stringify(d.settings));if(typeof d.holidays==='boolean')localStorage.setItem('fc_holidays_enabled',d.holidays?'1':'0')}const q=F.query(F.collection(db,'calendarBackups'),F.where('ownerUid','==',uid),F.limit(240));const snap=await F.getDocs(q);snap.forEach(x=>{const d=x.data();if(d.storageKey&&d.data)localStorage.setItem(d.storageKey,JSON.stringify(d.data))});status(`✅ 設定とカレンダー ${snap.size}か月分を復元しました。再読み込みすると反映されます。`,'ok')}
function status(t,k=''){const e=$('#fc-ac-status');if(e){e.textContent=t;e.className=`fc-ac-meta ${k==='ok'?'fc-ac-ok':'fc-ac-warn'}`}}
async function link(kind){try{await firebase();let p;if(kind==='google')p=new F.GoogleAuthProvider();else{p=new F.OAuthProvider('apple.com');p.addScope('email');p.addScope('name')}await F.linkWithPopup(auth.currentUser,p);await backup();render();status(`✅ ${kind==='google'?'Google':'Apple'}アカウントに接続しました。UIDを維持したまま永続化しました。`,'ok')}catch(e){console.warn('[account]',e);const msg=e?.code==='auth/operation-not-allowed'?'Firebase Authenticationでこのログイン方法を有効にしてください。':e?.code==='auth/credential-already-in-use'?'このアカウントは既に別のFocusCalユーザーに接続されています。':e?.code==='auth/popup-blocked'?'ポップアップがブロックされました。Safariで再度お試しください。':(e?.message||'接続できませんでした。');status(msg,'warn')}}
function render(){const e=$('#fc-ac-state');if(!e)return;const u=auth?.currentUser,ps=providers();e.innerHTML=`<div class="fc-ac-meta">UID: ${u?.uid||'-'}</div><div class="fc-ac-meta">状態: ${u?.isAnonymous?'匿名アカウント':'永続アカウント'}</div><div class="fc-ac-meta">接続: ${ps.length?ps.join(', '):'なし'}</div>`}
function mount(){if($('#fc-account-overlay'))return;const s=document.createElement('style');s.textContent=CSS;document.head.appendChild(s);document.body.insertAdjacentHTML('beforeend',`<div id="fc-account-overlay"><div id="fc-account-sheet"><div id="fc-account-head"><div class="fc-ac-title">👤 FocusCalアカウント</div><div class="fc-ac-sub">匿名UIDをGoogle/Appleへリンクすると、共有関係を維持したまま機種変更後も同じFocusCalへ戻れるようになります。</div></div><div class="fc-ac-card" id="fc-ac-state"></div><div class="fc-ac-card"><button class="fc-ac-btn primary" id="fc-ac-google">Googleと接続</button><button class="fc-ac-btn" id="fc-ac-apple">Appleと接続</button><div class="fc-ac-meta" style="margin-top:8px">Firebase Console側で対象プロバイダを有効にした後に使用できます。</div></div><div class="fc-ac-card"><button class="fc-ac-btn" id="fc-ac-backup">☁️ 設定・カレンダーをクラウド保存</button><button class="fc-ac-btn" id="fc-ac-restore">↺ クラウドから完全復元</button><div class="fc-ac-meta" style="margin-top:8px">個人用の非公開予定も本人専用バックアップとして保存します。共有用データとは別領域です。</div></div><div id="fc-ac-status" class="fc-ac-meta" style="margin-top:12px"></div></div></div>`);const settings=$('#settings-btn'),b=document.createElement('button');b.id='fc-account-btn';b.className='nav-btn';b.textContent='👤';b.title='アカウント';settings?.parentNode?.insertBefore(b,settings);b.onclick=async()=>{await firebase();render();$('#fc-account-overlay').classList.add('open')};$('#fc-account-overlay').onclick=e=>{if(e.target.id==='fc-account-overlay')e.currentTarget.classList.remove('open')};$('#fc-ac-google').onclick=()=>link('google');$('#fc-ac-apple').onclick=()=>link('apple');$('#fc-ac-backup').onclick=backup;$('#fc-ac-restore').onclick=restore;if(window.FocusCalSheetGestures){const h=window.FocusCalSheetGestures.ensureHandle($('#fc-account-sheet'),$('#fc-account-head'));window.FocusCalSheetGestures.attach($('#fc-account-sheet'),h)}}
function run(){mount();window.FocusCalAccount={backup,restore,build:BUILD}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();})();