(()=>{'use strict';
const BUILD='70';
const $=s=>document.querySelector(s),pad=n=>String(n).padStart(2,'0');
const key=(y,m)=>`fc_${y}_${m}`;
function readMonth(y,m){try{return JSON.parse(localStorage.getItem(key(y,m)))||{}}catch{return{}}}
function writeMonth(y,m,v){localStorage.setItem(key(y,m),JSON.stringify(v));}
function mins(t){if(!t)return 0;const [h,m]=t.split(':').map(Number);return h*60+m}
function hm(v){return `${pad(Math.floor(v/60))}:${pad(v%60)}`}
function overlaps(a,b,c,d){return a<d&&c<b}
function eventsFor(date){const raw=readMonth(date.getFullYear(),date.getMonth());return raw[String(date.getDate())]?.events||[]}
function freeSlots(date,startMin,endMin,step=30){const busy=eventsFor(date).filter(e=>!e.done).map(e=>e.allday?[0,1440]:[mins(e.start||'00:00'),mins(e.end||e.start||'23:59')]);const out=[];for(let s=startMin;s+step<=endMin;s+=step){const e=s+step;if(!busy.some(([a,b])=>overlaps(s,e,a,b)))out.push([s,e])}return out}
function contiguous(slots,duration){const need=Math.ceil(duration/30);for(let i=0;i<slots.length;i++){let end=slots[i][1],n=1;for(let j=i+1;j<slots.length&&slots[j][0]===end;j++){end=slots[j][1];n++;if(n>=need)return[slots[i][0],end]}if(need===1)return slots[i]}return null}
function findSlot({deadline,duration,from='09:00',to='22:00'}){const now=new Date(),end=new Date(deadline+'T23:59:00');const d=new Date(now.getFullYear(),now.getMonth(),now.getDate());for(;d<=end;d.setDate(d.getDate()+1)){let s=mins(from),e=mins(to);if(d.toDateString()===now.toDateString())s=Math.max(s,Math.ceil((now.getHours()*60+now.getMinutes())/30)*30);const hit=contiguous(freeSlots(d,s,e),duration);if(hit)return{date:new Date(d),start:hit[0],end:hit[1]}}return null}
function addEvent(task,slot){const y=slot.date.getFullYear(),m=slot.date.getMonth(),d=String(slot.date.getDate()),raw=readMonth(y,m);raw[d]=raw[d]||{events:[]};raw[d].events=raw[d].events||[];raw[d].events.push({id:`auto_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,title:task.title,memo:`FocusCal 自動配置 · 期限 ${task.deadline}`,cat:'work',pri:task.priority||'high',allday:false,start:hm(slot.start),end:hm(slot.end),done:false,peekVisibility:'full',autoPlanned:true,createdAt:Date.now()});writeMonth(y,m,raw);return{y,m,d:+d,start:hm(slot.start),end:hm(slot.end)}}
const CSS=`#fc-ai-overlay{display:none;position:fixed;inset:0;z-index:196;background:rgba(4,4,10,.78);backdrop-filter:blur(10px);align-items:flex-end;justify-content:center}#fc-ai-overlay.open{display:flex}#fc-ai-sheet{width:min(720px,100%);max-height:92dvh;overflow:auto;background:var(--surface,#13131f);border:1px solid var(--border2,#2c2c46);border-radius:22px 22px 0 0;padding:12px 16px 30px}.fc-ai-title{font-size:.9rem;font-weight:900;margin:8px 0 4px}.fc-ai-sub{font-size:.58rem;color:var(--muted);line-height:1.6;margin-bottom:14px}.fc-ai-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.fc-ai-grid .wide{grid-column:1/-1}.fc-ai-in{width:100%;background:var(--bg2);border:1px solid var(--border2);border-radius:11px;color:var(--text);padding:11px;font-size:.7rem}.fc-ai-btn{border:0;border-radius:12px;padding:12px;font-weight:850;background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff;width:100%;margin-top:12px}.fc-ai-res{margin-top:12px;padding:11px;border:1px solid var(--border);border-radius:11px;font-size:.64rem;color:var(--text2);line-height:1.7}`;
function mount(){if($('#fc-ai-overlay'))return;const st=document.createElement('style');st.textContent=CSS;document.head.appendChild(st);document.body.insertAdjacentHTML('beforeend',`<div id="fc-ai-overlay"><div id="fc-ai-sheet"><div id="fc-ai-head"><div class="fc-ai-title">🧠 自動予定最適化</div><div class="fc-ai-sub">期限と必要時間から、既存予定にぶつからない最短の空き時間へ自動配置します。</div></div><div class="fc-ai-grid"><input id="fc-ai-title" class="fc-ai-in wide" placeholder="やること（例：資料作成）"><input id="fc-ai-duration" class="fc-ai-in" type="number" min="30" step="30" value="60" placeholder="必要分数"><input id="fc-ai-deadline" class="fc-ai-in" type="date"><input id="fc-ai-from" class="fc-ai-in" type="time" value="09:00"><input id="fc-ai-to" class="fc-ai-in" type="time" value="22:00"></div><button id="fc-ai-run" class="fc-ai-btn">空き時間に自動配置</button><div id="fc-ai-res" class="fc-ai-res">予定を入力してください。</div></div></div>`);const settings=$('#settings-btn');const b=document.createElement('button');b.className='nav-btn';b.id='fc-ai-btn';b.textContent='🧠';b.title='自動予定最適化';settings?.parentNode?.insertBefore(b,settings);const tomorrow=new Date(Date.now()+864e5);$('#fc-ai-deadline').value=`${tomorrow.getFullYear()}-${pad(tomorrow.getMonth()+1)}-${pad(tomorrow.getDate())}`;b.onclick=()=>$('#fc-ai-overlay').classList.add('open');$('#fc-ai-overlay').onclick=e=>{if(e.target.id==='fc-ai-overlay')e.currentTarget.classList.remove('open')};$('#fc-ai-run').onclick=()=>{const task={title:$('#fc-ai-title').value.trim(),duration:+$('#fc-ai-duration').value||60,deadline:$('#fc-ai-deadline').value,from:$('#fc-ai-from').value,to:$('#fc-ai-to').value};if(!task.title||!task.deadline)return $('#fc-ai-res').textContent='やることと期限を入力してください。';const slot=findSlot(task);if(!slot)return $('#fc-ai-res').textContent='指定した期間には必要な連続空き時間がありません。時間帯か期限を広げてください。';const r=addEvent(task,slot);$('#fc-ai-res').textContent=`✅ ${r.y}/${r.m+1}/${r.d} ${r.start}〜${r.end} に「${task.title}」を配置しました。`;navigator.vibrate?.(12);try{window.dispatchEvent(new Event('focuscal:data-changed'))}catch{}};if(window.FocusCalSheetGestures){const h=window.FocusCalSheetGestures.ensureHandle($('#fc-ai-sheet'),$('#fc-ai-head'));window.FocusCalSheetGestures.attach($('#fc-ai-sheet'),h)}}
function run(){mount();window.FocusCalAutoPlanner={findSlot,addEvent,build:BUILD}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();})();