(()=>{'use strict';
const BUILD='70',$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let auth,db,F,spaces=[];
const code=()=>Math.random().toString(36).slice(2,8).toUpperCase();
const CSS=`#fc-collab-overlay{display:none;position:fixed;inset:0;z-index:198;background:rgba(4,4,10,.78);backdrop-filter:blur(10px);align-items:flex-end;justify-content:center}#fc-collab-overlay.open{display:flex}#fc-collab-sheet{width:min(760px,100%);max-height:92dvh;overflow:auto;background:var(--surface,#13131f);border:1px solid var(--border2,#2c2c46);border-radius:22px 22px 0 0;padding:12px 16px 28px}.fc-co-title{font-weight:900;font-size:.9rem;margin:8px 0 4px}.fc-co-sub{font-size:.58rem;color:var(--muted);line-height:1.6}.fc-co-card{border:1px solid var(--border);border-radius:14px;padding:12px;margin-top:10px;background:rgba(255,255,255,.025)}.fc-co-row{display:flex;gap:7px}.fc-co-in{flex:1;min-width:0;background:var(--bg2);border:1px solid var(--border2);border-radius:10px;color:var(--text);padding:10px;font-size:.66rem}.fc-co-btn{border:1px solid var(--border2);background:var(--surface2);color:var(--text);border-radius:10px;padding:10px;font-size:.64rem;font-weight:800}.fc-co-btn.primary{background:linear-gradient(135deg,var(--accent),var(--accent2));border:0}.fc-co-space h4{font-size:.72rem;margin-bottom:6px}.fc-co-meta{font-size:.54rem;color:var(--muted);line-height:1.6}.fc-co-event{padding:8px 0;border-top:1px solid var(--border);font-size:.62rem}`;
async function firebase(){if(auth)return;const cfg=window.FOCUSCAL_FIREBASE_CONFIG;const a=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),u=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js'),f=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js');const app=a.getApps().length?a.getApp():a.initializeApp(cfg);auth=u.getAuth(app);db=f.getFirestore(app);F={...f,...u};if(!auth.currentUser)await u.signInAnonymously(auth)}
async function createSpace(){await firebase();const name=$('#fc-co-name').value.trim();if(!name)return;const invite=code(),ref=F.doc(F.collection(db,'spaces'));await F.setDoc(ref,{name,ownerUid:auth.currentUser.uid,memberUids:[auth.currentUser.uid],inviteCode:invite,createdAt:F.serverTimestamp()});await F.setDoc(F.doc(db,'spaceCodes',invite),{spaceId:ref.id,createdAt:F.serverTimestamp()});$('#fc-co-name').value='';listen()}
async function joinSpace(){await firebase();const invite=$('#fc-co-code').value.trim().toUpperCase();if(!invite)return;const c=await F.getDoc(F.doc(db,'spaceCodes',invite));if(!c.exists())return alert('招待コードが見つかりません。');const sid=c.data().spaceId,ref=F.doc(db,'spaces',sid),s=await F.getDoc(ref);if(!s.exists())return;const members=Array.from(new Set([...(s.data().memberUids||[]),auth.currentUser.uid]));await F.updateDoc(ref,{memberUids:members});$('#fc-co-code').value='';listen()}
async function addSharedEvent(sid){const title=prompt('共同予定のタイトル');if(!title)return;const date=prompt('日付 YYYY-MM-DD');if(!/^\d{4}-\d{2}-\d{2}$/.test(date||''))return alert('YYYY-MM-DDで入力してください');const start=prompt('開始 HH:MM（終日なら空欄）')||'',end=prompt('終了 HH:MM（任意）')||'';await F.addDoc(F.collection(db,'spaceEvents'),{spaceId:sid,title,date,start,end,createdBy:auth.currentUser.uid,createdAt:F.serverTimestamp()})}
async function render(){const root=$('#fc-co-list');root.innerHTML='';for(const s of spaces){const wrap=document.createElement('div');wrap.className='fc-co-card fc-co-space';wrap.innerHTML=`<h4>${esc(s.name)}</h4><div class="fc-co-meta">招待コード ${esc(s.inviteCode||'-')} · ${s.memberUids?.length||1}人</div><div class="fc-co-row" style="margin-top:8px"><button class="fc-co-btn primary add">＋共同予定</button><button class="fc-co-btn copy">コードコピー</button></div><div class="events"><div class="fc-co-meta" style="margin-top:8px">読み込み中…</div></div>`;wrap.querySelector('.add').onclick=()=>addSharedEvent(s.id);wrap.querySelector('.copy').onclick=()=>navigator.clipboard?.writeText(s.inviteCode||'');root.appendChild(wrap);const q=F.query(F.collection(db,'spaceEvents'),F.where('spaceId','==',s.id),F.limit(50));F.onSnapshot(q,snap=>{const ev=snap.docs.map(d=>d.data()).sort((a,b)=>`${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`));wrap.querySelector('.events').innerHTML=ev.length?ev.map(e=>`<div class="fc-co-event"><b>${esc(e.date)}</b> ${esc(e.start||'終日')} ${esc(e.title)}</div>`).join(''):'<div class="fc-co-meta" style="margin-top:8px">共同予定はまだありません。</div>'})}}
async function listen(){await firebase();const q=F.query(F.collection(db,'spaces'),F.where('memberUids','array-contains',auth.currentUser.uid),F.limit(30));F.onSnapshot(q,snap=>{spaces=snap.docs.map(d=>({id:d.id,...d.data()}));render()})}
function mount(){if($('#fc-collab-overlay'))return;const st=document.createElement('style');st.textContent=CSS;document.head.appendChild(st);document.body.insertAdjacentHTML('beforeend',`<div id="fc-collab-overlay"><div id="fc-collab-sheet"><div id="fc-collab-head"><div class="fc-co-title">🤝 共同スペース</div><div class="fc-co-sub">恋人・家族・チームで同じ予定を作るための共有領域です。</div></div><div class="fc-co-card"><div class="fc-co-row"><input id="fc-co-name" class="fc-co-in" placeholder="スペース名（例：ふたりの予定）"><button id="fc-co-create" class="fc-co-btn primary">作成</button></div><div class="fc-co-row" style="margin-top:8px"><input id="fc-co-code" class="fc-co-in" placeholder="招待コード"><button id="fc-co-join" class="fc-co-btn">参加</button></div></div><div id="fc-co-list"></div></div></div>`);const settings=$('#settings-btn'),b=document.createElement('button');b.className='nav-btn';b.id='fc-collab-btn';b.textContent='🤝';b.title='共同スペース';settings?.parentNode?.insertBefore(b,settings);b.onclick=async()=>{await listen();$('#fc-collab-overlay').classList.add('open')};$('#fc-collab-overlay').onclick=e=>{if(e.target.id==='fc-collab-overlay')e.currentTarget.classList.remove('open')};$('#fc-co-create').onclick=createSpace;$('#fc-co-join').onclick=joinSpace;if(window.FocusCalSheetGestures){const h=window.FocusCalSheetGestures.ensureHandle($('#fc-collab-sheet'),$('#fc-collab-head'));window.FocusCalSheetGestures.attach($('#fc-collab-sheet'),h)}}
function run(){mount();window.FocusCalCollaboration={build:BUILD}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();})();